### ISSUE TITLE
My application call Navigator in render section, is it a problem?

### ISSUE THREAD

**Issue by itagakixt** [react-native-community/react-native-elements#100]
hello,

Using react-native-hackathon-starter, I incorporated one application into this environment.
My application is calling Navigator in render section.
I wonder this kind of using Navigator will make a problem or not.
I did not study deeply both environment.

Currently my application seems to works without error.

I 'm afraid futures problem.

Any suggestion or any pointer will be appreciated.

Thanks
Shoji

**Comment by dabit3** [comment]
Hey @itagakixt thanks for reporting this.  I see you reported this as well in the RN Hackathon Starter repo so I will take a look there and close this issue. Thanks.
