### ISSUE TITLE
[Button] Adjust gap between icon and text?

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-elements#101]
Would be great if we could adjust the gap between the icon and text. I'm unsure how this is set; applying 0 to margin and padding does not seem to adjust this distance.

![screen shot 2016-11-30 at 11 40 51 am](https://cloud.githubusercontent.com/assets/4974609/20761740/f6f5ad8e-b6f1-11e6-95c7-e7fe8d0ac9b6.png)

**Comment by dabit3** [comment]
Hello @joncursi , you should be able to do something like `textStyle={{ marginLeft: 20 }}` . I tried it and it seems to be working, but let me know if you can't get it to work and I'll reopen!

**Comment by goxr3plus** [comment]
How you did that i tried :

```
 <Button
               title="Add Goal"
               textStyle={{ marginLeft: 20 }}
               icon={<Icon name="plus" size={15} color="white" />}
               onPress={addGoalHandler}
            />
```

and it's still the same .

**Comment by f4th4n** [comment]
For latest react native elements, You can try this one:

`
<Button
     title="Add Goal"
     titleStyle={{ marginLeft: 50 }}
     icon={<Icon name="plus" size={15} color="white" />}
     onPress={addGoalHandler}
  />
`

**Comment by goxr3plus** [comment]
Thank you i will try :)

**Comment by MahamidRawi** [comment]
what about touchableopacity, how do we do that ?

**Comment by Estevete** [comment]
Is it possible to keep the button title in the middle of the button, and place the icon on one side?

Something like:
![image](https://user-images.githubusercontent.com/19273351/121350306-cbcdbe80-c92a-11eb-893b-5951722cd9d7.png)
