### ISSUE TITLE
[ListItem] Support Custom Elements

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-elements#102]
Sometimes you need a ListItem with a custom primary and/or secondary elements, rather than going with a simple string. For example, rendering 5 star icons for a reviews-centric ListItem.

![screen shot 2016-11-30 at 2 42 25 pm](https://cloud.githubusercontent.com/assets/4974609/20768268/45883ba6-b70b-11e6-89ff-88897982b5b9.png)

Allowing the passing of React Elements into ListItem will give the component much more flexibility for developers to use.

**Comment by xiaoneng** [comment]
#103

**Comment by Monte9** [comment]
@xiaoneng Thanks for updating the propTypes such that it accepts an object as well. Although that was not the complete solution. 

I added additional code such that it handles this object in the render method and renders it appropriately depending on whether it's just a string or an object. 

@joncursi I was able to mock the image that you attached as a demo for this feature. Check it out>
![screen shot 2016-12-23 at 2 00 58 pm](https://cloud.githubusercontent.com/assets/7840686/21463031/51b91dd6-c918-11e6-85ed-10332eebf815.png)

And here's the code for your reference:
```javascript
<ListItem
          roundAvatar
          title='Limited supply! Its like digital gold!'
          subtitle={
            <View style={{flexDirection: 'row'}}>
              <Image source={require('../images/stars.png')} style={{height: 19.21, width: 150}}/>
              <Text>5 months ago</Text>
            </View>
          }
          subtitleContainerStyle={{paddingLeft: 10, paddingTop: 5, paddingBottom: 5}}
          avatar={require('../images/avatar1.jpg')}
         />
```

**Comment by Monte9** [comment]
@dabit3 In terms of functionality, the subtitle can be a View or and Object but I think the title should still be **require** and still strickly a **String**. 
Thoughts?

**Comment by dabit3** [comment]
@Monte9 that sounds like it makes a lot of sense to me. I've also added badge and title props to this in a push either yesterday or the day before.

**Comment by Monte9** [comment]
Sounds good. @joncursi this should be out in the next release 0.9.0
