### ISSUE TITLE
[ButtonGroup] Should Support Icons

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-elements#105]
A common paradigm I've seen is to use icons instead of text within a ButtonGroup. Rather than assuming the input to be a string (being opinionated and wrapping the button within `<Text></Text>`), perhaps we should type check the button first. If string, wrap within text. If object (React element, perhaps an Icon), do not wrap within `<Text>`.

Right now, attempting to feed in an icon results in an error due to the `<Text>` wrap:

![screen shot 2016-12-01 at 12 45 02 pm](https://cloud.githubusercontent.com/assets/4974609/20805381/5d0f000c-b7c4-11e6-8975-1ba446de6c9c.png)

**Comment by joncursi** [comment]
Example: Venmo

![img_3155](https://cloud.githubusercontent.com/assets/4974609/20805404/87d04594-b7c4-11e6-8810-a6c5a7642bd7.PNG)

**Comment by dabit3** [comment]
Thanks @joncursi , this has just been added! To implement, provide an array of objects with an element key:
`[{element: someComponent}, {element: someComponent2}]`

**Comment by joncursi** [comment]
@dabit3 very impressed with your quick turnaround, thank you for adding this!

**Comment by huiming1313** [comment]
@dabit3 do you mind to share how to change the background / text colour when changing the selection when using the elements?

**Comment by Deg5112** [comment]
Awesome thanks!

**Comment by rosalynpoort** [comment]
> @dabit3 do you mind to share how to change the background / text colour when changing the selection when using the elements?

is there a way to change the selected button's icon color?

**Comment by thanhluantl2304** [comment]
> > @dabit3 do you mind to share how to change the background / text colour when changing the selection when using the elements?
> 
> @dabit3 is there a way to change the selected button's icon color?

same question! any update on this?

**Comment by Monkeystation** [comment]
To change the selected icon color you can use the selectedIndex variable, like so:

`const [selectedIndex, setSelectedIndex] = useState(0);`
`const component1 = () => <Icon name="flag" color={selectedIndex === 0 ? '#fff' : '#000'} />;`
`const component2 = () => <Icon name="room" color={selectedIndex === 1 ? '#fff' : '#000'} />;`
`const buttons = [{ element: component1 }, { element: component2 }];`
