### ISSUE TITLE
0.7.0 version button fontSize invalid string, expected number

### ISSUE THREAD

**Issue by zzzkk2009** [react-native-community/react-native-elements#106]
<Button
            buttonStyle={styles.loginBtn}
            onPress={this.onButtonPress}
            fontSize='18'
            title="登录"
          />

when  i use button component and set fontSize like that ,i got the warning:
![image](https://cloud.githubusercontent.com/assets/3713481/20820380/d9f1622a-b875-11e6-8841-3c456467354f.png)

Warning: Failed prop type: Invalid prop 'fontSize' of type 'string' supplied to 'Button', expected 'number'

but,i modify fontSize={18} or fontSize=18, is also wrong!

**Comment by dabit3** [comment]
Thanks for pointing this out!

**Comment by Dmitrylolo** [comment]
have same issue

**Comment by iRoachie** [comment]
Hey @Dmitrylolo can you a create a new issue? This issue is 2 years old.

**Comment by Dmitrylolo** [comment]
@iRoachie resolved it by textStyle={{ fontSize: 24 }}
