### ISSUE TITLE
`TabBarIOS.Item` hit React.Children.only expected to receive a single React element child

### ISSUE THREAD

**Issue by StTraft** [react-native-community/react-native-elements#107]
Hit this issue on `TabBarIOS.Item`.
if I return something like this in `render`:
```
<View>
  <TabBarIOS>
    <TabBarIOS.Item selected={true}>
      <View style={shouldBeNull}/>
    </TabBarIOS.Item>
  </TabBarIOS>
</View>
```
It will be fine, but if I removed the `<View style={shouldBeNull}/>`:
```
<View>
  <TabBarIOS>
    <TabBarIOS.Item selected={true} />
  </TabBarIOS>
</View>
```
It dies.
Just wonder if it could accept 0 child, or must have exactly one child for it to work.
;)

**Comment by StTraft** [comment]
PS: sounds related to issue#71 wrote by @danikenan ;)

**Comment by dabit3** [comment]
Hmmm. I think this has more to do with React Native than this particular project, but if not please reopen and let me know! Thanks :)

**Comment by StTraft** [comment]
Just dig a bit deeper, and @dabit3 you are correct. That is a problem coming from children check in `StaticContainer` in react-native, not including `undefined` as a false condition @_@
I think we can pass a `{null}`, or even a `{false}` as a workaround, the draw back is making the codes looks weird XD
