### ISSUE TITLE
[ListItem] Varying Right Icon Size

### ISSUE THREAD

**Issue by juddey** [react-native-community/react-native-elements#108]
Hey Nader -

Would you accept a PR that allows configuration of the size of the right icon on ListItem? 

Something like: 
```
rightIcon={{name: 'times', type: 'font-awesome', size: 10 }}
```
the default would still stay at 28 if you didn't specify a size.

Using this in a project right now. :)

**Comment by juddey** [comment]
I've wound up ditching this in favour of something else, so I'm giving it the :boot:.

**Comment by Viktor19931** [comment]
Does it work with size key ?
