### ISSUE TITLE
Error with Jest when importing from react-native-elements

### ISSUE THREAD

**Issue by ngduc** [react-native-community/react-native-elements#112]
Hi,
I got this error when using Jest to test a simple component which imports from react-native-elements. If I remove the import, the test will pass.

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ContactUsView`.
```

My test:
```
import React from 'react'
import {
    View,
    Text
} from 'react-native'
import { Button } from 'react-native-elements'
import baseStyles from '../baseStyles'

export default class ContactUsView extends React.Component {

  render () {
    return (
      <View style={baseStyles.view}>
        <Text style={baseStyles.h3}>
          Contact Us
        </Text>

        <Button
          raised
          backgroundColor={baseStyles.BRAND}
          icon={{ name: 'info-circle', type: 'font-awesome' }}
          title="Go to About Us"
          onPress={() => this.props.nav.linkTo('about')}
          buttonStyle={baseStyles.link}
        />
      </View>
    )
  }
}
```

Jest configs in package.json
```
"jest": {
    "moduleDirectories": [
      "node_modules",
      "app"
    ],
    "testEnvironment": "jsdom",
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|apsl-react-native|react-clone)"
    ],
    "moduleNameMapper": {
      "react-native": "<rootDir>/node_modules/react-native-web"
    }
  }
```
![image](https://cloud.githubusercontent.com/assets/639189/21197788/96232d5a-c1f1-11e6-8158-d8a28751f970.png)

Please check. Thanks.

**Comment by remon-georgy** [comment]
My gut feeling is it's related to react@15.3. Upgrading to 15.4 might fix it.

**Comment by ngduc** [comment]
@remon-georgy I upgraded react to 15.4.1, still got the same error.

**Comment by robbykim** [comment]
@ngduc getting the same error too

**Comment by dabit3** [comment]
Hmm, I'm not sure what is causing this. @ngduc @robbykim any ideas for a fix? If so I can get it in asap, if not, I'm not sure but still looking into it.

**Comment by binoy14** [comment]
I am not having this issue. Tried with enzyme (Need react-native-mock to use this package) and react-test-renderer both. I am using the following versions.

- Jest: 18.0.0
- react: 15.4.1
- react-native: 0.39.2
- enzyme: 2.7.0
- react-native-mock: 0.2.9 (Only required if using enzyme)

**Comment by binoy14** [comment]
@ngduc @robbykim Are you still have this issue?

**Comment by robbykim** [comment]
i'm good now. using jest 18.0.0, react 15.4.2, react-native 0.39.2

**Comment by phuquoc** [comment]
Hello, i'm a newbie on ReactNative, I tried to learn about react-native-elements from this example https://snack.expo.io/rJu6gJfBZ 
I did not use Expo but run my apps on a virtual machine instead, I got the error below, I spent hours and hours to fix it but not worked :(((
![image](https://user-images.githubusercontent.com/20508535/55162393-0b53ca00-5168-11e9-933f-9a38a8fd6880.png)

I installed react-native-elements 1.1.0 and react-native-cli: 2.0.1 react-native: 0.52.3

PLEASEEE help me, many thanks
