### ISSUE TITLE
Feature request: add badges and labels and allow to use it in ListItem

### ISSUE THREAD

**Issue by benjaminb10** [react-native-community/react-native-elements#114]
The goal is to provide badges and labels like that:
![screenshot_2016-12-16 03 23 44_qram5e](https://cloud.githubusercontent.com/assets/2952678/21249547/14061978-c33f-11e6-858e-d0c72d2ef9a4.png)

And to use it in ListItem for a result like that:

![screenshot_2016-12-16 03 24 17_q4fin0](https://cloud.githubusercontent.com/assets/2952678/21249583/54cb66c0-c33f-11e6-9378-a3f17786db4b.png)

**Comment by dabit3** [comment]
@benjaminb10 This has been added and will be released along with the next release, probably version 0.8.0. Thanks for the idea!

**Comment by foxgolf** [comment]
hi
What props should I use to use text or label above the badge like the picture shown above?

https://cloud.githubusercontent.com/assets/2952678/21249583/54cb66c0-c33f-11e6-9378-a3f17786db4b.png

Thanks

**Comment by iRoachie** [comment]
Hey @foxgolf Here's how you could do it https://snack.expo.io/S1VlJK67X
