### ISSUE TITLE
How to set selectedTextStyle  for ButtonGroup ?

### ISSUE THREAD

**Issue by gillesBzk** [react-native-community/react-native-elements#117]
selectedBackgroundColor works well but when I try to set selectedTextStyle for ButtonGroup, it doesn't work

selectedBackgroundColor={'#B23704'} //ok
selectedTextStyle={'white'} // or selectedTextStyle={{'white'}} doesn't work

Thank's for your help

**Comment by dabit3** [comment]
I'll take a look at this today, thanks!

**Comment by dabit3** [comment]
Ok, it looks like this should be more like `selectedTextStyle={{ color: 'white' }}`

**Comment by Thierno2sow** [comment]
@dabit3 this does not work for selectedTextStyle={{ color: 'white' }}
