### ISSUE TITLE
I would like to ask this effect can be achieved?

### ISSUE THREAD

**Issue by jingxin2015** [react-native-community/react-native-elements#119]
![qq 20161222080658](https://cloud.githubusercontent.com/assets/16143766/21410767/33897540-c81e-11e6-94c1-767c649be68f.jpg)

Tab bar effect in the above figure, thanks.

**Comment by dabit3** [comment]
Hmm, that looks really nice, but I really don't think it's something I will be able to focus on at this moment, with all of the outstanding issues and roadmap. If you have an idea how to implement and would like to submit a pr, please do so, but for now I will close and possibly revisit in the future!
