### ISSUE TITLE
I don't find in this package a designed element for Navbar (NavigationBar)?

### ISSUE THREAD

**Issue by benjaminb10** [react-native-community/react-native-elements#120]
Hi,
I don't find in this package a designed element for Navbar (NavigationBar)?
Do you plan to add one?
Such like the Header component of NativeBase: http://nativebase.io/docs/v0.5.13/components#header

**Comment by Monte9** [comment]
Thanks for bringing this up @benjaminb10! We are talking about this here #47 
Feel free to join us there.
