### ISSUE TITLE
What kind approch is best to re-render(or reload) List class?

### ISSUE THREAD

**Issue by itagakixt** [react-native-community/react-native-elements#121]

**Comment by itagakixt** [comment]
I'm developing the react-native APL using react-native-hackathon-starter(Tab controller) and list-detail screen control (Navigator)
'''
  render() {
    return (
      // Handle navigation between screens
      <Navigator
        // Default to list route
        initialRoute={{name: 'list1'}}
        // Use FloatFromBottom transition between screens
      configureScene={(route, routeStack) => Navigator.SceneConfigs.FloatFromBottom} 
        // Pass a route mapper functions
        renderScene={RouteMapper}
      />
    );
  }
}
'''
Sign up, login processing is done at the account tab.

Login processing is implemented with Firebase authentication.

On the user tab, we acquire the current user id and display a list of logged-in user's information.

At the account tab, if the user logs out.

On the user tab, dose not reflect the logout and redisplay the previous user  information.

If the user logs in on a separate account tab, same dose not reflect the logout and redisplay the  previous user  information .

The problem is that the user tab's render does not occur after logging in and logging out.

I can retrieve the correct user by reloading the application and display it.

Two question

1. Can I control application reloading with React Native? such as CTRL-R on debbuger?

2. When login change processing was done with the account tab,
Can I re-load the user tab? as described Hierarchy here,

User Tab Class Hierarchy
RootContainer (come from react-native-hackathon-starter)
Nav  (come from react-native-hackathon-starter)
List    (this class needed reloaded including constructor)
Row
Detail (When change tab clicked, list item is tapped, render is started)

How to re-render(or reload) List class when login or logou is occured?
 
Thanks

Shoji

**Comment by Monte9** [comment]
hi @itagakixt,

From what I understand, if you need to re-render a component, you can change its state using the `this.setState` method and React Native will pick this up and re-render your component. You can use the `componentWillUpdate` method as this will be called each the component re-renders. 

I would recommend you look into the lifecycle methods for React Native. Check this link out for a start: http://www.reactnativeexpress.com/lifecycle_api

**Comment by itagakixt** [comment]
Thanks for reply and pointer,

I'm just studying the lifecycle methods for React Native.
Can I call this.setState from another class?
(in my APL, another Tab need to call this class)

Is there any way to call direct call?(if possible, from beginning constructor )  

redux may be a solution for this kind problem?

Thanks

    Mounting Cycle
    constructor(props) { super(props); this.state = { // state initial process } } 
    componentWillMount(){ // before render process } 
    shouldComponentUpdate(){ // view or not // return true or false} 
    render() { return( // View ); } 
    componentDidMount(){ // after render, DOM initial process } 
    Updating Cycle
    componentWillReceiveProps(nextProps){ // called when props is update} 
    componentWillUpdate(nextProps, nextState){ // before Component update } 
    componentDidUpdate(prevProps, prevState){ // after Component update} 
    componentWillUnmount(){ // called when deleted Component} }
