### ISSUE TITLE
Custom style not being applied

### ISSUE THREAD

**Issue by jrmcdona** [react-native-community/react-native-elements#122]
Hi-
btnFb style is not being applied here.   I want to change the width of these buttons as they are uneven.   

What am I doing wrong here?

<Button
              backgroundColor='#3b5998'
              icon={{ name: 'facebook', type: 'entypo', buttonStyle: styles.btnFb }}
              onPress={() => this._signInFB()}
              title='Sign in with Facebook' />

const styles = StyleSheet.create({
  btnFb: {
    borderColor: '#CFCFCF',
    borderStyle: 'solid',
    borderWidth: .5,
    width: 300,
    paddingVertical: 10
  },
  btnGoogle: {
    borderColor: '#CFCFCF',
    borderStyle: 'solid',
    borderWidth: .5,
    width: 300,
    paddingVertical: 10,
    backgroundColor: '#dd4b39',
    paddingTop:10
  },
});

**Comment by dabit3** [comment]
I think you may need to do it like this: `icon={{ name: 'facebook', type: 'entypo', style: styles.btnFb }}`

**Comment by jrmcdona** [comment]
Hi Nader,
I am simply trying to control the width of the button not the icon.  

Is the only way to control with of a button through the "large" setting?   I wanted to be more precise but cannot find anything in the docs.  
This didn't work either.   

<Button
              style={styles.btnGoogle}
              backgroundColor='#dd4b39'
              icon={{ name: 'google-', type: 'entypo' }}
              title='Sign in with Google'
              onPress={() => this.props.actions.signInGoogle()}
               />

**Comment by dabit3** [comment]
Ah, ok have you tried `<Button buttonStyle={ styles. btnFb }`

**Comment by jrmcdona** [comment]
shoot, I thought I had.  BUt that works.

**Comment by AjithBharathi** [comment]
<Button buttonStyle={ styles. btnFb } this is not change my button width

**Comment by AjithBharathi** [comment]
<Button
                 buttonStyle={styles.btn2}
                onPress={this.clickme}
                title="ADD"
                color="#841584"
/>
      btn2: {
        width:'100%',
        },      

this is my button coding, anybody give me a suitable solution for me

**Comment by xavier-villelegier** [comment]
@AjithBharathi If you are using `v1.0.0-beta3` you need to set both `containerStyle` and `buttonStyle` to set the width. There is an opened PR about that #1000
