### ISSUE TITLE
Unable to load an image in Card component

### ISSUE THREAD

**Issue by bozzmob** [react-native-community/react-native-elements#123]
Hi,

I am unable to successfully load an image in the Card component.
I am trying to reuse the example shown in the README file and here is my code-

```

<View style={styles.container}>
  <Card
    title='HELLO WORLD'
    image={require('../imgs/rfood.png')}>
    <Text style={{marginBottom: 10}}>
      The idea with React Native Elements is more about component structure than actual design.
    </Text>
    <Button
      icon={{name: 'code'}}
      backgroundColor='#03A9F4'
      fontFamily='Lato'
      buttonStyle={{borderRadius: 0, marginLeft: 0, marginRight: 0, marginBottom: 0}}
      title='VIEW NOW' />
  </Card>
</View>
```

I haven't done any change as such, except for the image url. require isn't fetching the URL and the whole card is blank.
Whereas, an example with simple text(Headings H1,H2,etc.,) works fine.

I tried the URI version by giving the web URI as well. It didn't work either.

```
 image={uri:'https://lbb.in/bangalore/wp-content/uploads/sites/2/2015/09/nh8-rajasthani-thali.png'}>
```

Please let me know what am I missing. Spent couple of hours on this already.

<img src="https://cloud.githubusercontent.com/assets/1252941/21467992/004ebfaa-ca26-11e6-9102-e062a5816a58.png" alt="alt text" width="400" height="640">

<img src="https://cloud.githubusercontent.com/assets/1252941/21467991/004e4002-ca26-11e6-8397-453fe59ec44e.png" alt="alt text" width="400" height="640">

**Comment by bozzmob** [comment]
Facing the same issue with the Card component example with thumbnail images(profiles)
Using the same code as-is in the example.

![screenshot_20161224-223202](https://cloud.githubusercontent.com/assets/1252941/21468087/3dbf163e-ca29-11e6-9daa-4dee3a682cc1.png)

**Comment by bozzmob** [comment]
I'm sorry, my bad. Issue was, I wasn't using the styles.image property.

**Comment by LoriKarikari** [comment]
@bozzmob what style did you add to the image? 
I have used the imageStyle prop but it isn't showing only that line like on your screenshots
```
<Card
      title="test"
      image={require('../../assets/images/test.jpg')}
      imageStyle={styles.image}
    >
</Card>

const styles = StyleSheet.create({
  image: {
    width: 300,
    height: 300
  }
});
```

**Comment by SirPhemmiey** [comment]
Anyone solved this issue?

**Comment by iRoachie** [comment]
@SirPhemmiey Can you open a new issue? A lot has changed since 2016

**Comment by cparello** [comment]
<Card title={(newsapi_news) ? newsapi_news.title : ''}
                                      image={{uri: (newsapi_news) ? newsapi_news.url_to_image : ''}}
                                      imageStyle={styles.image}>
