### ISSUE TITLE
ListItem should be full width

### ISSUE THREAD

**Issue by iRoachie** [react-native-community/react-native-elements#124]
Currently the List has a space on the left for indenting the list. However this spacing should be applied to the ListItem so that when using underlayColor, the entire item would be selected.

**Current**
![screen shot 2016-12-24 at 4 34 35 pm](https://cloud.githubusercontent.com/assets/5962998/21468694/2cc39792-c9f7-11e6-88b1-ccb15c6de0b0.jpg)

**Expected**
![screen shot 2016-12-24 at 4 37 26 pm](https://cloud.githubusercontent.com/assets/5962998/21468698/553d4326-c9f7-11e6-80de-60e440772e07.jpg)

I achieved the expected by doing a `marginLeft: -15` on the containerStyle prop of the List. 
Then on the ListItem `wrapperStyle={{ paddingLeft: 15 }}`

This should be the default behavior as this is how the native UITableView is.

**Comment by Monte9** [comment]
@iRoachie Good catch! And I agree with you.. this should be the default behavior as well. 
I have made the fix as seen below:
![fix](https://cloud.githubusercontent.com/assets/7840686/21468869/b839ad64-c9e0-11e6-8202-863a7994e3e1.png)
The fix should be out on our next release [v0.9.0](https://github.com/react-native-community/react-native-elements/tree/v0.9.0)

**Comment by iRoachie** [comment]
Thanks @Monte9 Great library

**Comment by Monte9** [comment]
Thanks @iRoachie! Feel free to file more issues if you think something else needs to be fixed or can be improved.
