### ISSUE TITLE
Roboto-Bold is not an Android system font

### ISSUE THREAD

**Issue by ar-maged** [react-native-community/react-native-elements#126]
I'm trying to run a simple Exponent app (that utilizes some elements like `Button`, `FormLabel` & `FormInput`) on a physical device (Sony Xperia Z3 Dual running Android 6.0.1), but I get this error:

<img src="https://cloud.githubusercontent.com/assets/11808903/21471937/d9cb3e38-cacc-11e6-9d3e-9857ff14de3a.png" width="300">

What can I do (apart from passing a `fontFamily` prop to every single component in the app) that would fix this problem?

**Comment by ricbermo** [comment]
I had the same issue. I solve it by downloading the font and placing it into assets/fonts and adding it to Font.loadAsync like this guide shows: https://docs.getexponent.com/versions/v12.0.0/guides/using-custom-fonts.html

**Comment by Monte9** [comment]
Thanks for the solution @ricbermo!
/cc @ar-maged
