### ISSUE TITLE
Add Profile Component

### ISSUE THREAD

**Issue by binoy14** [react-native-community/react-native-elements#129]
In the docs it says the profile component is in progress. Is there any progress on that If not I can make a PR if i can get a mockup of it.

**Comment by dabit3** [comment]
![profileexample](https://cloud.githubusercontent.com/assets/1857282/21578818/bb1dc618-cf54-11e6-9e5e-b0d0e86b4189.jpg)
Here is a basic example of what we had in mind, but feel free to improve upon it.
It should have the following props, title, subtitle, description, call to action (optional), array of icons (optional), but again feel free to improve / tweak if you decide to submit a pr!

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to use this issue to talk about this feature and ping @binoy14 or me (@monte9) if you feel like you can submit a PR for this. Thanks in advance.

Also you can track the status of this feature and all other roadmap features [here](https://github.com/react-native-community/react-native-elements/issues/195#issuecomment-286213704).
