### ISSUE TITLE
Tile Component

### ISSUE THREAD

**Issue by binoy14** [react-native-community/react-native-elements#130]
It would be great if we can add a Tile component similar to [this](http://shoutem.github.io/docs/ui-toolkit/components/tiles). Any thoughts?

![Tile Component](http://shoutem.github.io/img/ui-toolkit/tiles/large-tile@2x.png)

**Comment by dabit3** [comment]
So would this in theory be something like a square sized component with an image background ,a title and a subtitle?

**Comment by binoy14** [comment]
Yes in a way. If you check the link there are good example use of it.

**Comment by Monte9** [comment]
Those examples looks really good. Would be a good addition to elements imo.

**Comment by binoy14** [comment]
@Monte9 @dabit3 Need some suggestions on the usage code for Tile Component. Attaching screenshots and code for different tiles possible let me know what you guys think of it.

## Featured Tile

```
<Tile
   imageSrc={{uri: 'https://images.pexels.com/photos/253366/pexels-photo-253366.jpeg?w=1920&h=1080&auto=compress&cs=tinysrgb'}}
   title="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores dolore exercitationem"
   featured
   caption="Some Caption Text"
/>
```

![screen shot 2017-01-15 at 9 50 15 pm](https://cloud.githubusercontent.com/assets/6476108/21969491/beea4630-db6c-11e6-8913-7cc8813e35d6.png)

## Featured Tile with Icon

```
<Tile
  imageSrc={{uri: 'https://images.pexels.com/photos/253366/pexels-photo-253366.jpeg?w=1920&h=1080&auto=compress&cs=tinysrgb'}}
  icon={{name: 'play-circle', type: 'font-awesome'}}
  featured
/>
```

![screen shot 2017-01-15 at 9 50 22 pm](https://cloud.githubusercontent.com/assets/6476108/21969581/6004e408-db6d-11e6-9379-556a0c5e967a.png)

## Tile

```
<Tile
  imageSrc={{uri: 'https://images.pexels.com/photos/253366/pexels-photo-253366.jpeg?w=1920&h=1080&auto=compress&cs=tinysrgb'}}
  title="Lorem ipsum dolor sit amet, consectetur"
  icon={{name: 'play-circle', type: 'font-awesome'}}  // optional
>
  // Can be custom code
  <View style={{flex: 1, flexDirection: 'row', justifyContent: 'space-between'}}>
    <Text>Caption</Text>
    <Text>Caption</Text>
  </View>
</Tile>
```

![screen shot 2017-01-15 at 9 50 34 pm](https://cloud.githubusercontent.com/assets/6476108/21969683/fce073f0-db6d-11e6-8d03-6e42c15627a9.png)

**Comment by Monte9** [comment]
@binoy14 This looks great! I'll look at it in detail this weekend and follow-up on it. Thanks.

**Comment by wilomgfx** [comment]
+1

**Comment by shubham2385** [comment]
how can i give height and width

**Comment by iRoachie** [comment]
Hey @shubham2385 please create a new issue!
