### ISSUE TITLE
SocialIcon does not work onPress

### ISSUE THREAD

**Issue by leandro-a-silva** [react-native-community/react-native-elements#135]
Nothing happens by pressing the SocialIcon button, can I do something wrong?

```js
  <SocialIcon
    title='Connect with Facebook'
    button
    style={styles.Button__Facebook}
    type='facebook'
    onPress={() => {
      Alert.alert('Alert Title', 'Alert message.');
  }}/>
```

**Comment by bozzmob** [comment]
+1

I am facing the same issue. I thought it was only for me, and maybe some implementation has gone wrong with my code.
But, tried everything possible. onPress() doesn't work.

**Comment by Monte9** [comment]
@leandro-a-silva @bozzmob Good catch. I figured out why `onPress` was not being called. Turns out you need to pass it an `onLongPress` as well. 
This should work:
```js 
<SocialIcon
  title='Connect with Facebook'
  button
  style={styles.Button__Facebook}
  type='facebook'
  onPress={() => { 
    Alert.alert('Alert Title', 'Alert message.');
  }}
  onLongPress={() => {
    Alert.alert('Alert Title', 'Alert message.');
  }}
/>
```

IMO the `onLongPress` should be an optional and it should work with only an `onPress` as well. Will fix this in v0.9.0 and close out the issue once it's done.

**Comment by leandro-a-silva** [comment]
Thanks @Monte9!

**Comment by tafelito** [comment]
Hey Guys, I still have this issue and I'm already in 0.9.0, were you able to fix it?

Thanks

**Comment by Nickman87** [comment]
Also having this issue

**Comment by Monte9** [comment]
Will look into this today. Keep an eye out for a new subversion with the fix soon.

**Comment by Nickman87** [comment]
@Monte9 I overlooked it yesterday, but I think I found the source of this issue: https://github.com/react-native-community/react-native-elements/commit/0d700408a52b8e87a8cff801fd205ab081703922#commitcomment-20402978

**Comment by Monte9** [comment]
@Nickman87 Great find! You are right.. the bug was introduced in that commit. 
I updated the logic as per your suggestion. Thanks. 

The fix is on now master. Will publish the changes to npm soon.

**Comment by Nickman87** [comment]
@Monte9 Did you also verify ListItem.js? I think it has the same issue but I cannot verify at the moment.

**Comment by Monte9** [comment]
I did. I don't think it should effect that as the logic for `ListItem` is as below:
```let Component = onPress || onLongPress ? TouchableHighlight : View```

**Comment by Monte9** [comment]
Just publised v0.9.2 to npm. It has the fix for this bug.
Thanks for bringing this up, @leandro-a-silva!

**Comment by Nickman87** [comment]
Awesome, thanks! ListItem is working correctly indeed, I verified yesterday :). Great work with the components!

**Comment by chocobuckle** [comment]
I seem to be having this same bug in v0.17.0 ...'onPress' only working when I also include 'onLongPress'. Anyone else experiencing this again?

**Comment by chocobuckle** [comment]
In fact, even if I remove 'onPress' and just include 'onLongPress' then the latter is behaving the same as 'onPress' - the event is triggered whether I do a normal press or a long press.
