### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by joecaraccio** [react-native-community/react-native-elements#136]
Apologies in advance because I think this is more me and not actually an issue, but I can't seem to get badges to appear on a list view item. Here is how I am calling it:

`  <ListItem
            roundAvatar
            onPress={this.flist.bind(this)}
            title="Friends!"
            badge={{ value: 3}}
            hideChevron={true}
             />`

**Comment by joecaraccio** [comment]
Any advice would be great!

**Comment by Blinnikov** [comment]
@joecaraccio Do you have any custom styles defined on List/ListItem components? May be your badge is just hidden or placed  out of visible space. Your example works for me.

**Comment by Monte9** [comment]
@joecaraccio This works for me too. 

If you still need help to resolve this for your use case, I'll leave this issue open? Let me know.

**Comment by UXDart** [comment]
I had a similar problem, and it was because the release on npm didn't had the badge file... not sure if that was fixed on newer releases.... HTH

**Comment by binoy14** [comment]
Sounds like this is not an issue anymore so closing it. Feel free to open it if it's still an issue
