### ISSUE TITLE
UNMET PEER DEPENDENCY react-native-vector-icons@4.0.0

### ISSUE THREAD

**Issue by binzailani3136** [react-native-community/react-native-elements#140]
Yesterday, react-native-vector-icons@4.0.0 was released.
And react-native-elements requires react-native-vector-icons@3.0.0 as peer dependency.
![screen shot 2017-01-07 at 3 07 54 pm](https://cloud.githubusercontent.com/assets/20284956/21740157/2104f7b2-d4eb-11e6-9f6c-e044cf208310.png)
Could you please rise up the version of react-native-vector-icon mentioned on peer dependency in package.json file?
Can I PR for this small change? :)
Thanks

**Comment by manguluka** [comment]
I recently pushed a PR updating the version and adding the new MaterialCommunityIcons type : #141

**Comment by Monte9** [comment]
PR merged into master (current v0.9.1). Closing this issue.

**Comment by binzailani3136** [comment]
Great!
Thanks for your work.
