### ISSUE TITLE
Material Community Icons and Exponent

### ISSUE THREAD

**Issue by LoriKarikari** [react-native-community/react-native-elements#142]
Hi,

I want to use this package with Exponent but it doesn't work because it requires an unknown module "@exponent/vector-icons/MaterialCommunityIcons". These icons aren't supported by Exponent (yet) and I think this issue is related to #141. Is it possible to exclude these icons for Exponent? I downgraded to version 0.9.0 which is working fine.

Thanks

**Comment by manguluka** [comment]
There seems to be an issue open for this on Exponent's fork (exponent/vector-icons#4). 

I'm not familiar with Exponent, but If no one answers in the next few days I'll try put together a pull request with the updates.

**Comment by hugotox** [comment]
+1

**Comment by manguluka** [comment]
This should work now, exponent/vector-icons#4 has been closed.

**Comment by Monte9** [comment]
Thanks for the updates @manguluka! 

@LoriKarikari can you confirm that it solves your issue? I'll close this issue once you do so.

**Comment by LoriKarikari** [comment]
Working perfectly with react-native-elements 0.9.2 and @exponent/vector-icons 4.0.0.

**Comment by ajiprasetyo** [comment]
how i can downgrade react-native-elements on ubuntu ?

**Comment by binoy14** [comment]
@ajiprasetyo you can change the version in package.json and run npm install. It might good idea to delete the react-native-elements folder from node_modules first
