### ISSUE TITLE
 Consider a mention to react-native-easy-grid

### ISSUE THREAD

**Issue by sanketsahusoft** [react-native-community/react-native-elements#143]
Thanks for using the Grid, Row and Col components from [React Native Easy Grid](https://github.com/GeekyAnts/react-native-easy-grid/) (NativeBase).

A mention to the same would be greatly appreciated!

Keep up the good work!

**Comment by SupriyaKalghatgi** [comment]
+1

**Comment by Monte9** [comment]
@sanketsahusoft Updated!

**Comment by sanketsahusoft** [comment]
@Monte9 Thanks for that! See you tomorrow at GeekyAnts!

I didn't know you were one of the contributors of `react-native-elements`. **Small world!**
