### ISSUE TITLE
FormLabel should not force to uppercase

### ISSUE THREAD

**Issue by peacechen** [react-native-community/react-native-elements#145]
FormLabel forces text to uppercase with `children.toUpperCase()`.  It would be more flexible if it left the contents as-is to allow the consumer to decide exactly what to put inside.  Alternatively for backwards compatibility, I could introduce a prop that allows the consumer to control whether to uppercase the text (defaulting to the current behavior).

**Comment by dabit3** [comment]
Thanks @peacechen this will be updated in release 9.4
