### ISSUE TITLE
How to modify the backgroundColor of the Button when disabled ,

### ISSUE THREAD

**Issue by q351941406** [react-native-community/react-native-elements#146]
How to modify the backgroundColor of the Button when disabled ,

**Comment by Monte9** [comment]
Check out Issue #152. I'll close out this issue if adding a `disableStyle` will solve this for you. 
Let me know and we can move this discussion over there.

**Comment by dabit3** [comment]
@q351941406 looks like this has been added and will be released with 0.9.4 today!

**Comment by Monte9** [comment]
This feature is available in the latest release of RNE.
