### ISSUE TITLE
Multiple FormInput refs clobber others' refs

### ISSUE THREAD

**Issue by peacechen** [react-native-community/react-native-elements#147]
Assume there are two `FormInput`s :
```
<FormInput
  placeholder={'First Name'}
  ref='myForm'
  textInputRef='firstName'
/>

<FormInput
  placeholder={'Last Name'}
  ref='myForm'
  textInputRef='lastName'
/>
```

The behavior is that each FormInput replaces the ref `myForm` entirely, clobbering any previous refs from other `FormInput`s.  `this.refs.myForm.refs` contains only `lastName`, not `firstName`. 

It would be much more useful to be able to group all the form refs under one object.  Otherwise it's difficult to iterate over refs not knowing which ones belong to the form.  If the current behavior is by design, I would like to understand why it is this way and how to iterate over refs belonging just to the form.

**Comment by Monte9** [comment]
@peacechen For the current implementation, I would suggest discussing it with @dabit3. 

As far as changing the behaviour such that it groups all the form refs under one object.. I like that idea. Would you be able to submit a PR with such an implementation? I would be more than happy to merge it if it enhances the form refs functionality.

**Comment by peacechen** [comment]
I'll put it on my list for when I have some breathing room.  Thanks for being open to a PR.

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to use this issue to talk about this feature and ping @binoy14 or me (@monte9) if you feel like you can submit a PR for this. Thanks in advance.

Also you can track the status of this feature and all other roadmap features [here](https://github.com/react-native-community/react-native-elements/issues/195#issuecomment-286213704).
