### ISSUE TITLE
Unable to resolve module @exponent/vector-icons/MaterialCommunityIcons ...

### ISSUE THREAD

**Issue by mrdezzods** [react-native-community/react-native-elements#150]
I'm having an issue installing this module with exponent. When installing, I got some warning 'react-test-renderer@15.4.2 requires a peer of react@^15.4.2 but none was installed.'

and when I try to build by app, I get the following error. What is the reason for this and how do I solve it?

Thank you
![image](https://cloud.githubusercontent.com/assets/7695060/22041909/11569e26-dd09-11e6-9383-41aacc19cb7c.png)

**Comment by binoy14** [comment]
What version of react-vector-icons are you using? react-native-elements 0.9+ uses version 4 of react-vector-icons

**Comment by mrdezzods** [comment]
@binou14 thanks mate. Apparently that was the problem.
