### ISSUE TITLE
Do you plan to add Hn components?

### ISSUE THREAD

**Issue by benjaminb10** [react-native-community/react-native-elements#151]
Just like HTML Hn tags (h1, h2, h3, ...) with different font-size, do you plan to add Hn components?
If not, do you have react-native package to recommand?

**Comment by Monte9** [comment]
Can you give some specific examples or a link to an HTML implementation of this that can be referenced? Thanks.

**Comment by benjaminb10** [comment]
Something like in bootstrap CSS framework: http://getbootstrap.com/css/#type

**Comment by sabativi** [comment]
This is already the case no ? See the docs

**Comment by Monte9** [comment]
@benjaminb10 This is already a part of React Native Elements. 

Check this out: https://github.com/react-native-community/react-native-elements#html-style-headings
