### ISSUE TITLE
Sidemenu - tap anywhere on the edge to close?

### ISSUE THREAD

**Issue by ngduc** [react-native-community/react-native-elements#156]
Hi,
I'm using the Sidemenu.
Normally, user should be able to tap anywhere on the edge to close the Sidemenu but it doesn't work now. I have to tap the menu icon to toggle it.
Is this supported? Thanks.

**Comment by dabit3** [comment]
@ngduc I don't think this has been added yet, I'll be checking into seeing if we can add it. Thanks!

**Comment by Monte9** [comment]
@ngduc This is supported. For a working example of this please check out [React Native Hackathon Starter](https://github.com/dabit3/react-native-hackathon-starter)

Also fyi:
`This component implements react-native-side-menu which is part of the react-native-community.`
