### ISSUE TITLE
Tab bar: is it possible to use tab bar with react-native-router-flux?

### ISSUE THREAD

**Issue by idlesong** [react-native-community/react-native-elements#157]
Anyone knows how to use tab bar with react-native-router-flux?
I'm a newbie of React-native, does there any guides or articles? 

RNRF seems need to put every tab in the 'Scene' and no place to put the RNE-tabs.

[react-native-router-flux tab bar example](https://github.com/aksonov/react-native-router-flux/blob/master/docs/DETAILED_EXAMPLE.md)
``` javascript
<Scene key="tabbar" tabs={true} >
    <Scene key="tab1"  title="Tab #1" icon={TabIcon} navigationBarStyle={{backgroundColor:'red'}} titleStyle={{color:'white'}}>
        <Scene key="tab1_1" component={TabView} title="Tab #1_1" onRight={()=>alert("Right button")} rightTitle="Right" />
        <Scene key="tab1_2" component={TabView} title="Tab #1_2" titleStyle={{color:'black'}}/>
    </Scene>
  /*...*/
```

Thanks.

**Comment by Monte9** [comment]
@idlesong RNRF provides Tabs as well out of the box. Here's an example:
```
<Scene key={'tabs'} hideNavBar={true} tabs={true} tabBarStyle={styles.tabBar} direction={'vertical'}>
  <Scene/>
  ...
</Scene>
```

You can refer to documentation here: https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md#tabbar

Hence if you are using RNRF, there is not need for you to also use RNE-tabs. Hope this helps.

**Comment by manideepcs024** [comment]
can we dynamically change the tabcontents on basis of user type. I have to show different set of options for a admin and for seller.

**Comment by Monte9** [comment]
I think you would be able to do that, by rending different content with the tab component itself.

**Comment by manideepcs024** [comment]
but I have to update content dynamically i.e. tab icon and title on the basis of react store state. 
for that I need some help. how can I connect state to tabicon or at approuter.

**Comment by Monte9** [comment]
Your best bet is to post this question on the RNRF repo. I haven't used the library recently, and so I can't give you a very accurate answer. 

Also fyi, RNE has deprecated the dependency on`react-native-tab-bar` and we recommend using `react-navigation` instead. React Navigation also provides Tab Bar out of the box, so you should look into it and compare RNRF with React Navigation and see which one you would like to use.

Check out react navigation here: https://reactnavigation.org/
