### ISSUE TITLE
Bug: slider not start from left

### ISSUE THREAD

**Issue by pewh** [react-native-community/react-native-elements#159]
On react-native's built-in Slider, it shows correct behavior. But on react-native-element's `Slider`, it doesn't start from left, although I set `value={0}` in props. But react-native-element's `Slider` can be dragged manually to the left edge.

![a](https://cloud.githubusercontent.com/assets/881358/22324687/4cc8e8e4-e3dd-11e6-9c56-757a00cb0d9a.png)

**Comment by max2three** [comment]
@pewh This has been fixed in v0.9.4.

**Comment by pewh** [comment]
Thanks. It's work now
