### ISSUE TITLE
List of icons for buttons available?

### ISSUE THREAD

**Issue by charlieroth** [react-native-community/React-Native-Elements#16]
What icons are being used for the buttons. I know you can add them but what is the source of the icons? Fontawesome? Other source?

**Comment by dabit3** [comment]
Hey, you can use any [material icon name](https://design.google.com/icons/), but we probably need to make this more obvious in the docs. Maybe I'll put a not below the heading, or if you have any ideas of a good way to convey this, please lmk :) @charlieroth

**Comment by charlieroth** [comment]
Yeah my only suggestion would be to just say that the default icons come from Material Icons 👍 @dabit3 . Btw the way thank you for this package. You are doing an awesome job. Can't wait to see what the future holds!

**Comment by dabit3** [comment]
@charlieroth Thanks for the feedback, and thanks for the kind words :) Look forward to growing this project.
