### ISSUE TITLE
Edit style of right icon for ListItem

### ISSUE THREAD

**Issue by balibou** [react-native-community/react-native-elements#165]
Hello, Is there a way to edit the style of the right icon ?

**Comment by dabit3** [comment]
I'm pretty sure you can pass in `rightIcon={{ style: { marginLeft: 20, ...otherstyles }  }}` to the ListItem. Let me know if that does not work.

**Comment by dabit3** [comment]
@balibou Also try upgrading to 0.9.4 as I think this is new functionality maybe?

**Comment by balibou** [comment]
Hello @dabit3, it doesn't work ...
first I've updated to 0.9.4 no change.
then I tried to pass your object, but fails because it's expecting a string (name of the material icon)

**Comment by dabit3** [comment]
@balibou Hmm, I'm sorry about that. Checking it out now.

**Comment by dabit3** [comment]
@balibou just pushed a fix, version 0.9.5 should work for you.

**Comment by balibou** [comment]
@dabit3 sorry for the late, I will test it as soon as I can (was on holidays)

**Comment by Monte9** [comment]
@balibou I tested this and it works. 
Try this:
```rightIcon={{ name: 'arrow-right', type: 'font-awesome', style: { marginRight: 10, fontSize: 15 } }}```
Let me know if this works for you and i'll close the issue.

**Comment by balibou** [comment]
@Monte9 @dabit3 just tested it, it works ! Thanks a lot !
