### ISSUE TITLE
[Feature Request] Please add support for render buttons in searchbar

### ISSUE THREAD

**Issue by gperdomor** [react-native-community/react-native-elements#167]
I need a search bar with button on the right side like this:
![img_1471](https://cloud.githubusercontent.com/assets/371939/22532670/5dadd1bc-e8c7-11e6-8879-2550dd4a2c51.jpg)

:D

**Comment by binoy14** [comment]
@gperdomor While this might be a "hack" you can use the [Grid Component](https://github.com/react-native-community/react-native-elements#grid-component) and create two columns with the search bar in one column and button in another.
