### ISSUE TITLE
[Feature Request] Support custom component in avatar list items

### ISSUE THREAD

**Issue by gperdomor** [react-native-community/react-native-elements#171]
Hi... I need render custom avatar when the item has no image, something like user initials like this package does: https://github.com/avishayil/react-native-user-avatar

**Comment by Monte9** [comment]
@gperdomor This is a solid request. We are working on implementing this soon. Keep an eye out for v0.10.0

**Comment by Monte9** [comment]
@gperdomor The Avatar Component has been added to RNE. See this PR for more details on how it was implemented> (https://github.com/react-native-community/react-native-elements/pull/197)

The avatar component should be released with v0.10. Keep an eye out for that release and follow along [here](https://github.com/react-native-community/react-native-elements/issues/195) for updated.
