### ISSUE TITLE
FormInput in android and ios differend

### ISSUE THREAD

**Issue by CecilLee** [react-native-community/react-native-elements#173]
ios is right

![93302982](https://cloud.githubusercontent.com/assets/8233657/22747787/f8161228-ee62-11e6-8e77-4c49e21ce148.jpg)

android is wrong
![1704190561](https://cloud.githubusercontent.com/assets/8233657/22747786/f81519c2-ee62-11e6-8f83-c59a0280b08f.jpg)

**Comment by CecilLee** [comment]
form input bottom line align

**Comment by Monte9** [comment]
@CecilLee Can you share a code snippet that you are using that demonstrates this issue? Thanks.

**Comment by Monte9** [comment]
Closing this issue for now due to inactivity. Feel free to open it up again if you need help.
