### ISSUE TITLE
Search Bar text color not listening to inputStyle prop

### ISSUE THREAD

**Issue by temitope** [react-native-community/react-native-elements#174]
I am unable to get the SearchBar to be responsive to the value of the inputStyle prop. color remains unchanged and gray.

```
<SearchBar
            containerStyle={{borderWidth:1,backgroundColor:'#fff'}}
            inputStyle={{color:'#fff'}}
            placeholder='Find something...' />
```

**Comment by max2three** [comment]
@temitope If you are referring to the placeholder text color, you need to set the `placeholderTextColor` prop instead.

```
<SearchBar
  containerStyle={{borderWidth:1, backgroundColor:'#fff'}}
  inputStyle={{color:'#fff'}}
  placeholder='Find something...'
  placeholderTextColor='#fff' />
```

**Comment by temitope** [comment]
@max2three thanks! that is exactly what I was talking about. i didnt realize the style was different as the documentation does not specify this prop. huge help.

**Comment by max2three** [comment]
@temitope You are welcome. Actually the `SearchBar` [documentation](https://github.com/react-native-community/react-native-elements#searchbar-props) does mention that it inherits all native `TextInput` props along with some extra ones.

**Comment by temitope** [comment]
@max2three ahh yes, you're right, i saw that but just didnt follow the link...and it makes sense that you dont list all the inherited props.
