### ISSUE TITLE
Form onSubmitEditing doesn't transfer focus

### ISSUE THREAD

**Issue by Talkwondo** [react-native-community/react-native-elements#179]
Hi,
I am trying to use onSubmitEditing to pass to focus to the next textinput but I am getting an error.
could someone paste here an example how to make it?

Thanks,

**Comment by Monte9** [comment]
The `FormInput` component inherits all the properties from React Native `TextInput`. Hence maybe this is a good place to start: https://facebook.github.io/react-native/docs/textinput.html

@binoy14 Anything you would like to add?

**Comment by binoy14** [comment]
@Talkwondo Seems like your problem is solved, hence closing this. If you still need help feel free to open it back.

**Comment by jasan-s** [comment]
I'm using redux-form and it seems there is a focus method here:  `this.Field.getRenderedComponent().refs.Field.__proto__.focus()` 

But when I call it I get the error Cannot read property 'textInputRef' of undefined 
the focus function looks like this: 

```
focus() {
      var ref = this.props.textInputRef;
      this.refs[ref].focus();
    }
```

Shouldn't the focus method do something like this:

```
focus() {
    TextInputState.focusTextInput(ReactNative.findNodeHandle(this));
  }
```

**Comment by binoy14** [comment]
@jasan-s PR #362 will fix this issue

**Comment by jasan-s** [comment]
looking forward to it. until then using simple TextInput
