### ISSUE TITLE
`View` has no propType for native prop `RCTView.flexGrow` of native type `float`

### ISSUE THREAD

**Issue by bluedusk** [react-native-community/react-native-elements#181]
Hi, I got this error when I tried run-ios, any idea what might the problem? Many thanks.

`View` has no propType for native prop `RCTView.flexGrow` of native type `float`
If you haven't changed this prop yourself, this usually means that your versions of the native code and JavaScript code are out of sync. Updating both should make this error go away.

verifyPropTypes
    verifyPropTypes.js:58
requireNativeComponent
    requireNativeComponent.js:90
<unknown>
    View.js:509
loadModuleImplementation
    require.js:122
<unknown>
    AppContainer.js:20
loadModuleImplementation
    require.js:122
<unknown>
    renderApplication.js:15
loadModuleImplementation
    require.js:122
<unknown>
    AppRegistry.js:19
loadModuleImplementation
    require.js:122
<unknown>
    index.ios.js:18
loadModuleImplementation
    require.js:122
guardedLoadModule
    require.js:58
global code
    require-0.js:1

**Comment by bozzmob** [comment]
How were you able to resolve it? Please do write it for community. It will surely help the community if they get the same issue.
