### ISSUE TITLE
[Feature] Add close icon props in SearchBar

### ISSUE THREAD

**Issue by abdurrahmanekr** [react-native-community/react-native-elements#182]
Hi, What do I have to do when I want to delete what I have written? 
Like SearchBar.closeIcon={true}. Thank you.

**Comment by binoy14** [comment]
@abdurrahmanekr There doesn't seem to be an close icon. I think it will be a great addition. Thanks for reporting

**Comment by Monte9** [comment]
Thanks for the PR @binoy14! 

@abdurrahmanekr the PR has been reviewed and will me merged soon. Keep an eye out for our next release v0.10. You can follow along with updates [here](https://github.com/react-native-community/react-native-elements/issues/195)
