### ISSUE TITLE
Invalid prop 'name' on icon

### ISSUE THREAD

**Issue by jenessawhite** [react-native-community/react-native-elements#183]
I am trying to use the material-community icon set and getting a warning of an `invalid prop "name" of value "checkbox-blank-outline" supplied to "icon"` any idea why?

`<Icon type='material_community' name='checkbox-blank-outline'/>`

**Comment by max2three** [comment]
@jenessawhite There is a typo for the `type` name. Just change it to

`<Icon type='material-community' name='checkbox-blank-outline' />`

**Comment by jenessawhite** [comment]
sorry, that was actually a typo when I typed it in here.
it does in fact say <Icon type='material-community' name='checkbox-blank-outline' />

**Comment by max2three** [comment]
@jenessawhite MaterialCommunityIcons was introduced in [4.0.0](https://github.com/oblador/react-native-vector-icons/releases/tag/v4.0.0).

What version of React Native are you using? `4.0.0` only works with RN `>=0.40`.

If you are on RN `>=0.40`, do the following to upgrade react-native-vector-icons:

1. `npm uninstall react-native-vector-icons --save`
2. `npm install react-native-vector-icons --save`
3. `react-native link react-native-vector-icons`

**Comment by binoy14** [comment]
@jenessawhite Closing this issue as it seems it fixed your problem. Let me know if otherwise.

**Comment by madeinquant** [comment]
@max2three According to your suggestion, this issue has been fixed. Thank you.

```
react-native-cli: 2.0.1
react-native: 0.59.9
```

```
1. yarn remove react-native-vector-icons
2. yarn add react-native-vector-icons
3. react-native link react-native-vector-icons
```

**Comment by Dlu6** [comment]
If you're using react-native-vector-icons try including /FontAwesome in the import like below;
import  Icon from 'react-native-vector-icons/FontAwesome';

There are some icons that are not included in /Ionicons which causes the error.
