### ISSUE TITLE
[Feature] Add featuredTile prop in Tile

### ISSUE THREAD

**Issue by RWOverdijk** [react-native-community/react-native-elements#188]
Not sure if this is the place to ask this but is it possible to combine tiles and cards? I like the `Featured Tile` tile with the text over the image, but I'd like that exact style in a card, in place of the image.

**Comment by binoy14** [comment]
@RWOverdijk Can you explain in detail what do you mean?

**Comment by RWOverdijk** [comment]
@binoy14 Detail.. Well, I'll try.

Cards allow this appearance:

![](https://camo.githubusercontent.com/c3b53dcb16b65a87a491c9a2dea0a412ace58714/687474703a2f2f692e696d6775722e636f6d2f625935754143332e706e67)

The left part, where there's a nice image, followed by a title, a paragraph and a button.

A Tile, allows you to do this:

![](https://cloud.githubusercontent.com/assets/6476108/21969491/beea4630-db6c-11e6-8913-7cc8813e35d6.png)

with text _over_ the image.

I would like to be able to use the card, like in the first image, but move the title into the image, like in the tile. Preferable in the bottom left, or top left corner. Is there some way I can style the title to do that? Or is there already a combination of elements supporting this?

I hope I make sense. Thanks!

**Comment by binoy14** [comment]
As per discussion with @RWOverdijk, We decided that have a prop `featuredTitle` which would move the title in a Tile (not featured tile) inside the image.

**Comment by RWOverdijk** [comment]
👍

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to use this issue to talk about this feature and ping @binoy14 or me (@monte9) if you feel like you can submit a PR for this. Thanks in advance.

Also you can track the status of this feature and all other roadmap features [here](https://github.com/react-native-community/react-native-elements/issues/195#issuecomment-286213704).
