### ISSUE TITLE
Can I use local image as CheckBox's checkedIcon & uncheckedIcon ?

### ISSUE THREAD

**Issue by DavidKongDesheng** [react-native-community/react-native-elements#191]
It looks like only support react-native-vector-icons~

**Comment by binoy14** [comment]
No it only supports react-native-vector-icons. I will look into if it's possible to do local image.

**Comment by Monte9** [comment]
I think for simplicity, we should stick to rendering Icons from `react-native-vector-icons` only.  In all my uses cases, I have almost never found a time when I could not find an icon I was looking for. So while it might be cool to support local images, in this case for Icons I think it might be an overkill. 

Open to hear your thoughts though. /cc @DavidKongDesheng @binoy14

**Comment by binoy14** [comment]
I agree icons mostly do the trick. Also `react-native-vector-icons` are font's so there won't be issues with scaling and stuff on different resolutions

**Comment by DavidKongDesheng** [comment]
Actually I agree with @Monte9, just notice that if we support both would be more user friendly and will make this kit much more powerful, we haven't met the cases that react-native-vector-icons can't cover, but nothing is impossible~
