### ISSUE TITLE
my button have just only gray background-color

### ISSUE THREAD

**Issue by panhna** [react-native-community/react-native-elements#192]
how to enable the background color back? thx

![screen shot 2017-02-22 at 12 47 56 am](https://cloud.githubusercontent.com/assets/5246440/23177308/eac3e498-f898-11e6-963e-3b82f63b7969.png)
![screen shot 2017-02-22 at 12 50 12 am](https://cloud.githubusercontent.com/assets/5246440/23177340/02e5e24c-f899-11e6-95b2-794368a77ecb.png)

**Comment by binoy14** [comment]
@panhna You can use the following snippet to change the color.

```
<Button
  raised
  buttonStyle={{backgroundColor:"blue"}}
  icon={{name: 'cached'}}
  title='BUTTON WITH ICON' />
```

I think the default color is grey but @Monte9 can comment on it if i am mistaken.

**Comment by panhna** [comment]
it's work for me. i just think that i miss something to make it work like screenshot.
thx for your advise.
