### ISSUE TITLE
Button  After pressing borderRadius Invalid

### ISSUE THREAD

**Issue by durongzhang** [react-native-community/react-native-elements#193]
系统：android 5.1.1

**Comment by binoy14** [comment]
@durongzhang Can you please explain in detail and provide either screenshots or code sample for us to understand what is the issue

**Comment by durongzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/15725537/23243328/0fda507a-f9b9-11e6-8ab6-9fa81b00cb09.png)
After pressing
![image](https://cloud.githubusercontent.com/assets/15725537/23243330/1792150a-f9b9-11e6-9c50-87f044ffc3b4.png)

**Comment by binoy14** [comment]
@durongzhang I'll take a look, Thanks

**Comment by binoy14** [comment]
@durongzhang I tried to recreate the issue your having but it is not happening for me. 

Here is the code I used.

```js
<Button
  borderRadius={25}
  buttonStyle={{backgroundColor:"#00BAC7"}}
  icon={{name: 'cached'}}
  title='BUTTON WITH ICON' />
```
![untitled](https://cloud.githubusercontent.com/assets/6476108/23283272/01feff66-f9f3-11e6-907e-426ccdb52860.gif)

What version are you using? Can you provide code snippets for us to look at?

**Comment by durongzhang** [comment]
"react-native-elements": "^0.9.7"
![image](https://cloud.githubusercontent.com/assets/15725537/23287373/e26b7e9c-fa77-11e6-8303-78c57e975790.png)
android:5.1.1
Manufacturer: coolpad
Estimation and system customization

**Comment by Monte9** [comment]
@durongzhang From what I gather there might be two ways to solve this:
1. The RNE Button component lets you pass in a `component` that overrides the default component on Android which is TouchableNativeFeedback. You can do this by passing a prop to button like so:
<Button
  component={TouchableOpacity}
  ... />

2. @binoy14 Found [this](https://github.com/facebook/react-native/issues/6480) thread that talks about a similar issue.
They suggest passing the `borderRadius` to the parent of the `TouchableNativeFeedback` component.. in this case wrap the `Button` in a view and add the borderRadius to that view. 

Let me know if either of those solutions work.

**Comment by Monte9** [comment]
Closing this issue as I haven't heard back from you @durongzhang. Feel free to open up the issue again if you need help.
