### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by binoy14** [react-native-community/react-native-elements#196]
Check out [Testing Branch](https://github.com/react-native-community/react-native-elements/tree/testing) for progress

Components to test

- [ ] Badge
- [x] Buttons
- [x] Checkbox
- [x] Form
- [ ] Grid
- [ ] Helpers
- [ ] Icons
- [ ] List
- [ ] Pricing
- [ ] Sidemenu
- [ ] Slider
- [ ] Social Buttons
- [ ] Tabs
- [x] Text
- [ ] Tile
- [ ] Divider

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to continue to use this issue to track progress.

**Comment by Monte9** [comment]
This issue is resolved. @binoy14 created and merged PR #231 for it.
