### ISSUE TITLE
Tile - require local asset not working

### ISSUE THREAD

**Issue by jeveloper** [react-native-community/react-native-elements#199]
RN 0.41.2

`imageSrc={{require: './assets/photo.jpg'}}`

Doesn't display an image. The asset is definitely there, i tested with

`require('./assets/photo.jpg')`

Also, tried passing a variable to imageSrc but is of type Object which creates warnings.

https://github.com/react-native-community/react-native-elements/blob/master/src/tile/FeaturedTile.js#L134

Please clarify if that example even works. 
thanks

**Comment by jeveloper** [comment]
Can i propose a solution to using required variable as a parameter 
that way you don't have to care where the image came from.

I normally initialize a constant once per component and then just pass it as a variable to e.g. imageSrc={_MYIMAGE}

**Comment by Monte9** [comment]
@jeveloper I tested this on my end and it seems to work for me. Let me know if this not what you are looking for.
```
<Tile
  imageSrc={require('../images/sample_image.jpg')}
  title="When I admire the wonders of a sunset or the beauty of the moon, my soul expands in the worship of the creator."
  titleStyle={{fontSize: 20}}
  featured
  caption="Mahatma Gandhi"
  activeOpacity={1}
  width={310}
  />
```

<img width="343" alt="screen shot 2017-02-25 at 6 17 23 pm" src="https://cloud.githubusercontent.com/assets/7840686/23336485/b03931b6-fb86-11e6-8c45-6a6e0b81db9d.png">

**Comment by binoy14** [comment]
@jeveloper You have an extra curly brace in `imageSrc={{require: './assets/photo.jpg'}}` I also tried requiring local asset and it works. 

That being said the proptypes for imageSrc needs to be updated.

**Comment by jeveloper** [comment]
hey @Monte9 thanks for checking this out

yes it works, its just 2-3 warnings would show up (blocking a part of the view) , because the result of

<Tile
  imageSrc={require('../images/sample_image.jpg')}

Is actually imageSrc is a number, binary here , PropTypes demand it be an object as  @binoy14 also mentions.

That is the bug i have filed :)

**Comment by binoy14** [comment]
@jeveloper It's fixed in https://github.com/react-native-community/react-native-elements/commit/adda797eeda811bc1b3fd7b6e6098bd3ba18abaf 

Thanks for reporting :)

**Comment by kimfucious** [comment]
[Tile Docs](https://react-native-training.github.io/react-native-elements/docs/tile.html) show 

`imageSrc={{ require: './img/path' }}` <= double curly braces

However, only the below works for me:

`imageSrc={( require: './img/path' )}` parens inside curly braces

**Comment by iRoachie** [comment]
@kimfucious I just sent a PR to update the docs, sorry about the confusion! https://github.com/react-native-training/react-native-elements/pull/1397

**Comment by iRoachie** [comment]
The fix is live! Thanks for reporting
