### ISSUE TITLE
Typeahead element

### ISSUE THREAD

**Issue by rodolfobarretoweb** [react-native-community/React-Native-Elements#20]
First of all, congratulations for all developers involved in this project, very good job.

My suggestion is to create a component to search data like bootstrap's typeahead (https://github.com/bassjobsen/Bootstrap-3-Typeahead)

In my personal project in react native, I have created one to fulfill my needs

When searching
https://drive.google.com/file/d/0B2MMFJxQwbxgR1BnQldyZ2hsWW8/view?usp=sharing

When selected
https://drive.google.com/file/d/0B2MMFJxQwbxgZl9LbEZMdTgwUVk/view?usp=sharing

**Comment by dabit3** [comment]
Oh wow, this looks great and is something I've also had to implement manually in the past. Care to share your previous implementation as a pull request, or do you think this is something you would like us to put on the roadmap? Thanks for your feedback!

**Comment by rodolfobarretoweb** [comment]
Please put in the roadmap.

**Comment by dabit3** [comment]
@rodolfobarretoweb done. Thanks again for the recommendation.
