### ISSUE TITLE
When passing styles from stylesheet in grid causes error

### ISSUE THREAD

**Issue by binoy14** [react-native-community/react-native-elements#209]
![screen shot 2017-03-04 at 6 00 32 pm](https://cloud.githubusercontent.com/assets/6476108/23582931/7e88f31c-0104-11e7-9a7b-621969e707a3.png)

This is because of this code snippet

```js
this.styles = {
   flex: 1,
   flexDirection: this.isRow() ? 'column' : 'row',
   ...style,
};
```

Problem Detail: When using StyleSheet.create it is a number type which is blocked by the Object.assign polyfill for performance. 

Solution: Change the style to how other components in react-native-elements are.

**Comment by Monte9** [comment]
Thanks for reporting the issue & submitting a PR. 

The PR has been reviewed. Feel free to close the issue when you merge the PR.
