### ISSUE TITLE
example code missing

### ISSUE THREAD

**Issue by martunta** [react-native-community/React-Native-Elements#21]
Looks like for each example code bit there is only first part visible. Is rest somehow gone missing, or it is not created yet?

**Comment by dabit3** [comment]
@martunta Thanks for pointing this out, we probably need to code samples that reflect closer to the ui screenshots. We'll update this soon!

**Comment by martunta** [comment]
there are really not that much of a difference. Screenshots still have a lot more information, examples do not match it. 

I am currently looking at ListView part of the docs - Using RN ListView. Implemented with link and avatar
from where this.state.dataSource comes from?

**Comment by dabit3** [comment]
@martunta The [ListView](https://facebook.github.io/react-native/docs/listview.html) is more of a React Native specific thing than a React Native Elements specific thing. I've tried to strike a balance between giving enough examples and not taking up too much space in the Readme. Check out the [React Native Hackathon Starter](https://github.com/dabit3/react-native-hackathon-starter) which does actually have most of these examples implemented. Also, feel free to reach out for specific implementations if you have any issues or future questions. Thanks!
