### ISSUE TITLE
Sticky list sub headers

### ISSUE THREAD

**Issue by jasan-s** [react-native-community/react-native-elements#218]
how can i add sticky subheaders for list items. [similar to this](https://github.com/emilsjolander/StickyListHeaders)

**Comment by Monte9** [comment]
@jasan-s RNE currently does not have any sort of functionality similar to sticky subheaders for lists. In fact, we do not even use `ListView` in any of the components.

Although if you found a RN library that did so, you could easily use it with `<List>` and `<ListView>` components.

**Comment by jasan-s** [comment]
@Monte9  what is the use of List component if I have to use Listview inside it? SOrry, I'm just trying to understand, why would i use it over just listview alone.
