### ISSUE TITLE
Scrolling in list view

### ISSUE THREAD

**Issue by Firaenix** [react-native-community/react-native-elements#22]
Hi,

I'm unsure whether or not I misread the documentation or otherwise, but I am unable to scroll the list view once the list of data surpasses the size defined by the maxHeight style.

Is there anyway for me to implement scrolling functionality?

Thanks

**Comment by dabit3** [comment]
Hey, yes you should probably wrap the list in a ScrollView. Will look into implementing the scrollview into List, may be a good idea to do so.

**Comment by ronak301** [comment]
Hey , why are you not using Listview of react-native to render list. It take care of scrolling and many many things. I think you might be knowing all this. So was there any specific reason , u have not choosen Listview

**Comment by dabit3** [comment]
You're welcome to use ListView or not, it's not coded into the actual implementation. Check out the docs where we use both a map function and a ListView to render the ListView elements.

**Comment by andrerfneves** [comment]
I think we should follow the same patterns react native core uses for simplicity and consistency. I don't think using a RN ListView automatically earns you a scrollable list. So I believe @dabit3's implementation right now is correct and the developer should be aware of difference between View and ScrollView.
