### ISSUE TITLE
Beginner Contributions?

### ISSUE THREAD

**Issue by tarang9211** [react-native-community/react-native-elements#222]
Hey guys! This seems like a great place to start contributing! How can I start helping out? Are there any instructions to set up the repo and begin contributing?

**Comment by Monte9** [comment]
We are working on solidifying a process which is more welcoming for first contributors. Will also have a good guide to contribute to the repo. 

Details coming soon. Stay tuned.

**Comment by binoy14** [comment]
Closing this since it is not really an issue. Contributing instructions will be added soon
