### ISSUE TITLE
leftIcon: name triggering a function

### ISSUE THREAD

**Issue by sigmazen** [react-native-community/react-native-elements#223]
Hi
Awesome library ... really enjoying its use, and apologies for the rather basic question.
I'm trying to change the `leftIcon` in `ListItem` based on a value on the `rowData`.
For example 1=local-airport   2=local-activity

The following function is doing the demo conversion:

      category2Icon(inCategory) {
        if (inCategory === 1) return 'local-airport';
        if (inCategory === 2) return 'local-activity';
      }

I can see that the function is being called inside the `ListItem` because the following works:

      renderRow (rowData, sectionID) {
        return (
          <ListItem
            leftIcon = {{ name: 'warning' }}
            onPress = { () => console.info(this.category2Icon(rowData.category))  }                           
            . . .
          /> 
        ) 
      }

but when I amend the leftIcon so that `name` calls the function, thus:

      renderRow (rowData, sectionID) {
        return (
          <ListItem
            leftIcon = {{ name: () => this.category2Icon(rowData.category) }}
            . . .
          /> 
        ) 
      }

I get an warning:

      Warning: Failed prop type: Invalid prop `name` of value `function name() {
            return _this2.category2Icon(rowData.category);
          }` supplied to `Icon`

Any ideas?
Thanks in advance
Cheers
Simon

**Comment by binoy14** [comment]
@sigmazen Seems like you cannot use function as name. Can you try the following code snippet and see if that works. 

```
renderRow (rowData, sectionID) {
   const iconName = this.category2Icon(rowData.category);
    return (
      <ListItem
        leftIcon = {{ name: iconName }}
        . . .
      /> 
    ) 
  }
```

**Comment by sigmazen** [comment]
Wow :-)   Thanks a million @binoy14  works perfectly
The concept of storing this stuff as a `const` is also a great learning for me.
Thanks again
