### ISSUE TITLE
crna issue  - unable to resolve module

### ISSUE THREAD

**Issue by prashantham** [react-native-community/react-native-elements#226]
Unable to resolve module @expo/vector-icons/glyphmaps/Zocial.json

**Comment by Monte9** [comment]
@binoy14 did you run into this?

**Comment by binoy14** [comment]
@prashantham that's a new one. Did you follow the instructions posted?

@monte9 I will also double check this on my end.

**Comment by prashantham** [comment]
Hi,
   I did follow the instructions as mentioned.
   But i am not able to replicate this now. Might be that expo dependency was not present in package.json. 
   This issue can be close now.

**Comment by prashantham** [comment]
I still do get the issue. I have a new app with runs fine on iOS app and simulator. But fails on Android device. Same as before Unable to resolve module @expo/vector-icons/glyphmaps/Zocial.json.

**Comment by binoy14** [comment]
@prashantham I will check it on my end too. I am closing this issue as its not related to react-native-elements, rather create-react-native-app. I will follow up with issue on that repo.

**Comment by prashantham** [comment]
ok. I just went back with react-native init.
