### ISSUE TITLE
CRNA issue -- Tab component example fails to run

### ISSUE THREAD

**Issue by felipecocco** [react-native-community/react-native-elements#227]
Running the tab component example in a clean build of CRNA yields the following:

![image](https://cloud.githubusercontent.com/assets/4644625/24014865/dc844adc-0a5c-11e7-9bf1-40c8771102e7.png)

**Comment by binoy14** [comment]
@felipecocco do you get the same issue when u use it with react native CLI?

**Comment by felipecocco** [comment]
@binoy14 Sorry, my mistake -- I did get the same error running it with the react native CLI. I failed to remove the  /* ... more tabs here */  comment, which was being interpreted as a child of the component. Deleting that line made it all work. My apologies!
