### ISSUE TITLE
tabBarOptions activeTintColor working for Label but not for Icon

### ISSUE THREAD

**Issue by sigmazen** [react-native-community/react-native-elements#228]
Hi
Within the tabBar, the _label_ changes color `activeTintColor` to `inactiveTintColor`  but the _icon_ doesn't.
However, if I convert back to use the raw `{ Icon }` from `react-native` it works okay, so looks like a tiny gremlin ?

Here's the relevant code:

      tabBarOptions: {
        activeTintColor: 'white',
        inactiveTintColor: 'black',    
        style: { backgroundColor: '#002663' },
        labelStyle: { fontWeight: 'bold' },
      }

and below is my tabBar within the navigationOptions ... as an aside I've also tried commenting/uncommenting style and changing it to `{{ color: 'white' }}`  to no avail.

      tabBar: {
        label: 'Home',
        icon: ({ tintColor, focused }) => (
          <Icon
            name={focused ? 'ios-home' : 'ios-home-outline'}
            type='ionicon'
            size={26}
    //        style = {{ color: tintColor }}
          />
        ),
      },

Thanks in advance
Cheers

**Comment by binoy14** [comment]
@sigmazen In the Icon you need to use color prop and not style prop. See the props for Icon in the documentation https://github.com/react-native-community/react-native-elements#icon-props

**Comment by sigmazen** [comment]
Awesome :-)   Not sure why I missed it in the docs :-(
Works a treat even including a nice ternary:
    `color={focused ? 'white' : 'black'}`
Thanks again @binoy14
