### ISSUE TITLE
Ionicon icons not working

### ISSUE THREAD

**Issue by paulinosantos** [react-native-community/react-native-elements#240]
Apparently 'ionicon' icons are not working properly. I get an 'Invalid prop name' error.

I've tried with 'font-awesome' and it's working.

<Icon name='ion-android-bicycle' type='ionicon' />

**Comment by szakhlypa** [comment]
Hi @paulinosantos 
Can you specify name you've tried to use?
`<Icon type='ionicon' name='ios-heart' />` works.
Also please make a note that [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) uses [http://ionicframework.com/docs/v2/ionicons/](http://ionicframework.com/docs/v2/ionicons/) for prop names.

**Comment by binoy14** [comment]
@paulinosantos did that solve your problem?

**Comment by paulinosantos** [comment]
Thanks @szakhlypa it was a naming issue. I followed the docs in the link you provided and now I have no problem. Thanks a lot!

**Comment by M-Jas** [comment]
Not opening the issue back up, but we could change the link in the docs to [react-native-vector-icons](http://ionicframework.com/docs/ionicons/) and not [ionic-icons](http://ionicons.com/). 
I was also having issues with some ionic icons not working(ex: ios-telephone-outline), it seems like the naming is off.
Granted the ionic site has a link to the new batch, but this could prevent more questions.

**Comment by binoy14** [comment]
@M-Jas I'll update it, thanks for the suggestion
