### ISSUE TITLE
Icon bug in Avatar component

### ISSUE THREAD

**Issue by joncursi** [react-native-community/react-native-elements#244]
Bug: https://github.com/react-native-community/react-native-elements/blob/master/src/avatar/Avatar.js#L98

`icon.type` is being fed into the `name` prop on icon, which is incorrect. It should be fed into the `type` prop:

```jsx
<Icon
   ...
  name={icon.name || 'user'}
  name={icon.type || 'material'}
  ...
/>
```

**Comment by darleikroth** [comment]
Yes. The documentation is completely different about this point.
[Avatar Props](https://github.com/react-native-community/react-native-elements#avatar-props)

`prop icon -> type ->
object {name: string, color: string, size: number, type: string (default is material, or choose one of material-community, simple-line-icon, zocial, font-awesome, octicon, ionicon, foundation, evilicon, or entypo), iconStyle: object(style)}`

**Comment by Monte9** [comment]
Will review this as part of the fix for #245.

**Comment by binoy14** [comment]
Closing this in favor of #245

**Comment by Monte9** [comment]
PR #269 has been merged!
