### ISSUE TITLE
Octicon blank on latest version

### ISSUE THREAD

**Issue by booboothefool** [react-native-community/react-native-elements#255]
I upgraded from 0.8.2 -> 0.10.2, which involved upgrading react-native-vector-icons from 3.0 -> 4.0, which blanked all of my `type="octicon"`. 😢 

e.g.

```
<Icon type="octicon" name="flame" />
```

was previously working.

`type="font-awesome"`, etc. still working.

**Comment by Monte9** [comment]
Consider looking at issues on the `react-native-vector-icons` repo. We haven't changes the way RNE consumes vector-icons. So seems most likely a change on the vector-icons side. Let me know if you come across a solution for this.

**Comment by binoy14** [comment]
@booboothefool try the solution in here if it helps,  https://github.com/react-native-community/react-native-elements/issues/183

**Comment by booboothefool** [comment]
@binoy14 

Ah, I am on RN 0.37 trying to use react-native-vector-icons 4.0.0. Seems like I am stuck. No worries.

**Comment by dineshmm23** [comment]
<Icon type="octicon" name="tools" size={24} color="#900" />

For these i am  getting an same warning ..
` "react-native-vector-icons": "^4.5.0"`
i am trying to get tools icon name from these[https://oblador.github.io/react-native-vector-icons/]

**Comment by xavier-villelegier** [comment]
@dineshmm23 Which warning are you talking about ?
