### ISSUE TITLE
ListItem Switch Component

### ISSUE THREAD

**Issue by Joshuabaker2** [react-native-community/react-native-elements#256]
It would be nice to have a Switch component available for the ListItem component for menus. Creating a PR to add this.

**Comment by Monte9** [comment]
@Joshuabaker2 You are THE definition of an ideal open-source contributor. Find something missing from a library, create an issue and also submit a PR that fixes that issue. 

Gj! I'll review the PR in a bit. Let's get it merged it today if possible.

**Comment by Joshuabaker2** [comment]
@Monte9 or @binoy14, mind taking a look at this one too? Luckily doesn't look like there's any merge conflicts with my other PRs which is nice.

**Comment by yash2code** [comment]
not working 

```javascript

<ListItem
                      //badge={{ value: 3, badgeTextStyle: { color: 'red' }, badgeContainerStyle: { paddingLeft:0, marginTop: 10, color:'orange' } }}
                      roundAvatar
                      title={`${item.name.first} ${item.name.last}`}
                      titleStyle={{ paddingLeft:50 }}
                      switchButton={true}
                      subtitle={item.email}
                      subtitleStyle={{ paddingLeft:50 }}
                      leftIcon={
                        <TouchableOpacity onPress ={ () => this._showModal()  }>
                        <Avatar
                        large
                       // onPress ={ () => this._showModal()  }
                        rounded
                        source={{ uri: item.picture.thumbnail }} 
                       containerStyle={{ flex:4, marginLeft:0 }}
                         />
                         </TouchableOpacity>
                             }
                    
                      containerStyle={{borderBottomWidth: 0, padding:0, paddingLeft:0 }}
                    />
```

**Comment by Monte9** [comment]
Thanks for reporting @yash2code. It would be most useful if you can create a Snack demo with the issue you create. 

Here's a good place to start: https://snack.expo.io/rJu6gJfBZ

**Comment by diegobfernandez** [comment]
@yash2code I had the same problem and found out that you have to set hideChevron with switchButton to actually display the switch. Checkout this Snack https://snack.expo.io/SJPQNScUZ

**Comment by Monte9** [comment]
@diegobfernandez Gj putting together the snack demo. Looks good. 👏

**Comment by alifa20** [comment]
@diegobfernandez 
You are a life saver. Would be good to add this into the readme file.

**Comment by Monte9** [comment]
@alifa20 agreed. I have added it to the docs [here](https://github.com/react-native-training/react-native-elements/commit/f211e0a3635734b84ae73a52c3353633a71c26d4) and it will be updated in the next release `v0.17`.
