### ISSUE TITLE
Getting error when using custom view for ListItem title - `Cannot add a child that doesn't have a CSS node to a node without a measure function!`

### ISSUE THREAD

**Issue by ronyv89** [react-native-community/react-native-elements#262]
I am trying to use a title view instead of a string. Like this
```
<ListItem
        key={rowData[0][1]}
        title={
          <View style={{ flex: 1 }}>
            <Text style={{ flex: 1 }}>5</Text>
          </View>
        }
/>
```

and I am getting this error:

![screen shot 2017-03-31 at 9 12 27 am](https://cloud.githubusercontent.com/assets/346546/24535513/3c9b2b20-15f2-11e7-94cd-aac4ee3eb2f6.png)

What could be the problem?

**Comment by binoy14** [comment]
Based on this https://github.com/facebook/react-native/issues/12284 it could be a bug, will investigate

**Comment by binoy14** [comment]
@ronyv89 I tested it in https://github.com/dabit3/react-native-hackathon-starter and it is not related to the code snippet you provided. It could be caused with some other part of your code. Closing this as it is not reproducible. If you are still having this issue feel free to open it back.
