### ISSUE TITLE
Add Grid component

### ISSUE THREAD

**Issue by dabit3** [react-native-community/react-native-elements#29]

**Comment by binoy14** [comment]
@dabit3 Any update on this? I can help out

**Comment by Monte9** [comment]
@binoy14 maybe we can implement something similar to this: https://github.com/GeekyAnts/react-native-easy-grid/ ?

**Comment by binoy14** [comment]
@Monte9 I have used that library before and it is very useful. Is there a contributing guide? I can take a stab at it.

**Comment by dabit3** [comment]
@binoy14 go for it! I'll be on the lookout for a pr.

**Comment by Monte9** [comment]
@binoy14 That would be great! There is no formal contributing guide, feel free to submit a PR and Nader ( @dabit3 ) and myself can take a look at it. 
Appreciate your help on this.

**Comment by binoy14** [comment]
I made Pull Request #127 Please review it.

A contributing guide would make it easier for people to contribute.

**Comment by dabit3** [comment]
@binoy14 checking it out now, thanks!

**Comment by Monte9** [comment]
Feature added to release v0.9.0. Closing this issue.
