### ISSUE TITLE
I am getting error PricingCard when I put color={colors.primary}

### ISSUE THREAD

**Issue by sanjibnarzary** [react-native-community/React-Native-Elements#32]
Please suggest me I am new to React as well React native still I manage to develop and run simple android application using React Native. The original react-native themes are very odd looking so I install this React-native-elements, for all it is working fine including PricingCard but when I put color={colors.primary} as attribute in the pricing Card the run time failure occurs. This gives the same error when I try creating styles for primary. Any help will be appreciated.

**Comment by dabit3** [comment]
@sanjibnarzary Thanks for pointing this out! The documentation was wrong, you can actually specify any color you would like! I've fixed the docs, thanks!

**Comment by sanjibnarzary** [comment]
Thank you for the quick reply, yes it solved my problem.
