### ISSUE TITLE
dependency on react-native-tab-navigator

### ISSUE THREAD

**Issue by crivera** [react-native-community/react-native-elements#36]
Hi

I am using Exponent and following your first step but when trying to use a button I get an error saying it cant find modules from https://github.com/exponentjs/react-native-tab-navigator 

is this intended? if yes it would be great to have it in the documentation

Thanks
Chris

**Comment by dabit3** [comment]
When I updated to the new version, I forgot to add the react-native-tab-navigator dependency. Either install react-native-tab-navigator or try installing the new version, 0.5.2, and this should be fixed. Sorry for the issue!!

**Comment by crivera** [comment]
awesome thanks!
