### ISSUE TITLE
side menu suggestion

### ISSUE THREAD

**Issue by forumics** [react-native-community/react-native-elements#37]
i've been trying to create a side menu that contains other menus
for example:
the side menu will contain these:
submenu #1 
submenu #2 
menuitem 1
menuitem 2

clicking on submenu #1 will bring me to:
submenu#1 item #1 
submenu#1 item #2 

clicking on submenu #2 will bring me to:
submenu#2item #1 
submenu#2item#2

clicking on menuitem # or submenu##item## will navigate to the object selected

perhaps with some small animation choice will be good as well

**Comment by dabit3** [comment]
@forumics Are those links correct? They are bringing me back to the github issues.

**Comment by forumics** [comment]
`import React, { Component } from 'react';
import {
  Dimensions,
  StyleSheet,
  ScrollView,
  Image,
  Navigator,
  TouchableWithoutFeedback,
  Animated,
    Easing,
    View,
    Text
} from 'react-native';


const window = Dimensions.get('window');
export default class Menu extends Component {
  constructor(props)
  {
    super(props);
      this.animatedValue = new Animated.Value(0);
    this.state = {
range1: 10,range2: -300,
range3: 300,range4: 10,
range5: 300,range6: 10,
display: 'main'
    };
  }



  animate() {
    this.animatedValue.setValue(0)
    Animated.timing(
      this.animatedValue,
      {
        toValue: 2,
        duration: 500,
        easing: Easing.in(Easing.ease),
      }
    ).start()
  }

startAnimation(item)
{
  if (this.state.display=='main' && item==1)
  {
    this.setState({range1:10, range2:-300, range3: 300, range4: 10, range5: 300, range6: 300, display: 'secondary'});
    this.animate();
  }
  if (this.state.display=='secondary' && item==1)
  {
    this.setState({range1:-300, range2:10, range3: 10, range4: 300, range5: 300, range6: 300, display:'main'});
    this.animate();
  }
  if (this.state.display=='main' && item==2)
  {
    this.setState({range1:10, range2:-300,range3: 300,range4: 300, range5: 300, range6: 10, display: 'secondary'});
    this.animate();
  }
  if (this.state.display=='secondary' && item==2)
  {
    this.setState({range1:-300, range2:10,range3: 300,range4: 300, range5: 10, range6: 300, display:'main'});
    this.animate();
  }

}

  render() {
    var mainMenu = this.animatedValue.interpolate({
        inputRange: [0, 1,2],
        outputRange: [this.state.range1, this.state.range2+5,this.state.range2]
      })
    var subMenu1 = this.animatedValue.interpolate({
        inputRange: [0, 1,2],
        outputRange: [this.state.range3, this.state.range4-5, this.state.range4]
      })
      var subMenu2 = this.animatedValue.interpolate({
          inputRange: [0, 1, 2],
          outputRange: [this.state.range5, this.state.range6-5,  this.state.range6]
        })
    return (
      <View>
      <View>
      <Animated.View style={{position: 'absolute', left: mainMenu}}>
      <Text onPress={() => this.startAnimation(1)}>submenu item 1</Text>
      <Text onPress={() => this.startAnimation(2)}>submenu item 2</Text>
      <Text>item 3</Text>
      <Text>item 4</Text>
      </Animated.View>
      </View>
      <View >
      <Animated.View style={{position: 'absolute', left: subMenu1}}>
      <Text onPress={() => this.startAnimation(1)}>return to main menu</Text>
      <Text>submenu 1 item 1</Text>
      <Text>submenu 1 item 2</Text>
      </Animated.View>
      </View>
      <View >
      <Animated.View style={{position: 'absolute', left: subMenu2}}>
      <Text onPress={() => this.startAnimation(2)}>return to main menu</Text>
      <Text>submenu 2 item 1</Text>
      <Text>submenu 2 item 2</Text>
      </Animated.View>
      </View>
      </View>
    );
  }
};

const styles = StyleSheet.create({
  menu: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    flex: 1,
    width: window.width+500,
    height: window.height,
    backgroundColor: 'gray',
    padding: 20,
    maxWidth: window.width+100
  },
  menu2: {
    position: 'absolute',
    left: 300,
    top: 0,
    bottom: 0,
    flex: 1,
    width: window.width+500,
    height: window.height,
    backgroundColor: 'gray',
    padding: 20,
    maxWidth: window.width+100
  },
  avatarContainer: {
    marginBottom: 20,
    marginTop: 20,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    flex: 1,
  },
  item: {
    fontSize: 14,
    fontWeight: '300',
    paddingTop: 5,
  },
});
`

**Comment by forumics** [comment]
import React, { Component } from 'react';
import {
  Dimensions,
  StyleSheet,
  ScrollView,
  Image,
  Navigator,
  TouchableWithoutFeedback,
  Animated,
    Easing,
    View,
    Text
} from 'react-native';


const window = Dimensions.get('window');
export default class Menu extends Component {
  constructor(props)
  {
    super(props);
      this.animatedValue = new Animated.Value(0);
    this.state = {
range1: 10,range2: -300,
range3: 300,range4: 10,
range5: 300,range6: 10,
display: 'main'
    };
  }



  animate() {
    this.animatedValue.setValue(0)
    Animated.timing(
      this.animatedValue,
      {
        toValue: 2,
        duration: 500,
        easing: Easing.in(Easing.ease),
      }
    ).start()
  }

startAnimation(item)
{
  if (this.state.display=='main' && item==1)
  {
    this.setState({range1:10, range2:-300, range3: 300, range4: 10, range5: 300, range6: 300, display: 'secondary'});
    this.animate();
  }
  if (this.state.display=='secondary' && item==1)
  {
    this.setState({range1:-300, range2:10, range3: 10, range4: 300, range5: 300, range6: 300, display:'main'});
    this.animate();
  }
  if (this.state.display=='main' && item==2)
  {
    this.setState({range1:10, range2:-300,range3: 300,range4: 300, range5: 300, range6: 10, display: 'secondary'});
    this.animate();
  }
  if (this.state.display=='secondary' && item==2)
  {
    this.setState({range1:-300, range2:10,range3: 300,range4: 300, range5: 10, range6: 300, display:'main'});
    this.animate();
  }

}

  render() {
    var mainMenu = this.animatedValue.interpolate({
        inputRange: [0, 1,2],
        outputRange: [this.state.range1, this.state.range2+5,this.state.range2]
      })
    var subMenu1 = this.animatedValue.interpolate({
        inputRange: [0, 1,2],
        outputRange: [this.state.range3, this.state.range4-5, this.state.range4]
      })
      var subMenu2 = this.animatedValue.interpolate({
          inputRange: [0, 1, 2],
          outputRange: [this.state.range5, this.state.range6-5,  this.state.range6]
        })
    return (
      <View>
      <View>
      <Animated.View style={{position: 'absolute', left: mainMenu}}>
      <Text onPress={() => this.startAnimation(1)}>submenu item 1</Text>
      <Text onPress={() => this.startAnimation(2)}>submenu item 2</Text>
      <Text>item 3</Text>
      <Text>item 4</Text>
      </Animated.View>
      </View>
      <View >
      <Animated.View style={{position: 'absolute', left: subMenu1}}>
      <Text onPress={() => this.startAnimation(1)}>return to main menu</Text>
      <Text>submenu 1 item 1</Text>
      <Text>submenu 1 item 2</Text>
      </Animated.View>
      </View>
      <View >
      <Animated.View style={{position: 'absolute', left: subMenu2}}>
      <Text onPress={() => this.startAnimation(2)}>return to main menu</Text>
      <Text>submenu 2 item 1</Text>
      <Text>submenu 2 item 2</Text>
      </Animated.View>
      </View>
      </View>
    );
  }
};

const styles = StyleSheet.create({
  menu: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    flex: 1,
    width: window.width+500,
    height: window.height,
    backgroundColor: 'gray',
    padding: 20,
    maxWidth: window.width+100
  },
  menu2: {
    position: 'absolute',
    left: 300,
    top: 0,
    bottom: 0,
    flex: 1,
    width: window.width+500,
    height: window.height,
    backgroundColor: 'gray',
    padding: 20,
    maxWidth: window.width+100
  },
  avatarContainer: {
    marginBottom: 20,
    marginTop: 20,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    flex: 1,
  },
  item: {
    fontSize: 14,
    fontWeight: '300',
    paddingTop: 5,
  },
});

**Comment by dabit3** [comment]
@forumics check out issue #115 we're going to be replacing this component with [react-native-side-menu](https://github.com/react-native-community/react-native-side-menu)
