### ISSUE TITLE
How is it different from NativeBase.io?

### ISSUE THREAD

**Issue by sanketsahusoft** [react-native-community/react-native-elements#38]
I am the core developer & the founder of NativeBase.io, I have been following React-Native-Elements for a while now.

I would like to discuss the possibility of merging NativeBase.io with this one. If we are solving the same problem then it doesn't make sense putting the same effort at different places.

Also, are we following any design guidelines (like Google / Apple design principles)?

**Comment by dabit3** [comment]
Hey, it's not really following any specific styling guidelines because they are all configurable with styling! Not sure I want to move it away from this repo, we are trying to keep it 100% free and open source. Isn't native base charging for some of the components?

**Comment by sanketsahusoft** [comment]
Hi @dabit3, thanks for the inputs! NativeBase is 100% Open source, it doesn't charge for its components.

Also, do you have any idea about how can we move NativeBase to react-native-community? What are the pros and cons of moving it to the react-native-community organization?

**Comment by dabit3** [comment]
@sanketsahusoft Oh that's awesome, I really like NativeBase, you guys have a lot of great components. Re: moving to RN Community, I would reach out to either @knowbody and check with him on what that process is.

**Comment by knowbody** [comment]
hey @sanketsahusoft!

> Also, do you have any idea about how can we move NativeBase to react-native-community? What are the pros and cons of moving it to the react-native-community organization?

Our goal is to keep FOSS, maintained and well documented modules for React Native within the organisation. If you want your project to join us, just ping me or other folks on the team (@grabbou, @satya164, @Kureev, @brentvatne) and we will make it happen.
We want react-native-community to be a "go to" place for high quality, well maintained modules for React Native.

* The **cons** - I can't think of any... We don't owe your code, we don't ask for for your npm access, you are still in full control of your repository.

* The **pros** - I think at some point it will attract more contributors to these projects. At the moment I see the pros for others, because they can be sure that when they use any of these modules they are well supported.

**Comment by sanketsahusoft** [comment]
@knowbody Thanks a lot for the inputs. I really appreciate that you and the community are open to embrace open source projects with value.

I will have an internal discussion with the team and ping you once we have some updates.

Thanks again!

**Comment by satya164** [comment]
Sounds awesome!

**Comment by ALawliet** [comment]
My project is currently a blend of NativeBase (most things), Elements (love the icons/buttons), and https://github.com/xinthink/react-native-material-kit (range sliders!!), so it'd be amazing if you guys did a merge! 👍

**Comment by pierredewilde** [comment]
Any update about a _potential_ merge of NativeBase into React Native Elements ?

**Comment by sanketsahusoft** [comment]
@pierredewilde No plans about the merge as of now. Both the repos are built on different patterns and a bit of different philosophies actually.

**Comment by herlarbs** [comment]
Is there any hope of a potential merge someway along the nearest future or have both parties decide to go on separate ways. I love Nativebase but I'm keen on its direction and path for the next foreseeable future

**Comment by rockus123** [comment]
I think javascript and react and angular and all these thousands of framework are the wrong way to go.  To complicated in everything.

**Comment by davebro** [comment]
@rockus123 Huh?? Why are you even here lol? People probably said the same thing during the Industrial Revolution...and uh...now I have a MacBook Pro. So.....

**Comment by Ayc0** [comment]
Is there any progress ?

**Comment by Jonovono** [comment]
@sanketsahusoft Hey, can you talk a bit about the differing philosophies in these two projects? :)

**Comment by sanketsahusoft** [comment]
@Jonovono 

* NativeBase follows the design guidelines of Android and iOS and aims at unifying their API using conditional styling.
* NativeBase suggests on adding more JSX and less props which makes it flexible.
* NativeBase defines the styling in one place which can be ejected and overridden by the user.

**Comment by eduardoinnorway** [comment]
Any progress here or just talks?
