### ISSUE TITLE
FormInput ref attribute

### ISSUE THREAD

**Issue by crivera** [react-native-community/react-native-elements#39]
Hi

i saw that FormInput is a stateless function and does not support the TextInput ref attribute. 

if i am on a login screen and want to type in my username and then password i am not able to jump between text inputs since the ref attribute doesnt work.

is there a workaround for this?

Thanks
Chris

**Comment by dabit3** [comment]
@crivera Just fixed this in the latest release. Thanks for bringing it to my attention !

**Comment by crivera** [comment]
awesome!
