### ISSUE TITLE
Need a ref to textInput component in FormInput

### ISSUE THREAD

**Issue by bikashsharmabks** [react-native-community/react-native-elements#42]
Hello,

I have requirement where I need to access the refs (references) of textInput component in react-native-elements FormInput component for some requirement for handling keyboard slide

Does the FormInput supports it, can we have this feature if its not at present?

Changes needed in file FormInput.js

```javascript
//line number 7
const FormInput = ({
  textInputRef,
  ....
})

//linenumber 51
  <TextInput
      ref = {textInputRef}

```

Thanks for sharing awesome components

**Comment by crivera** [comment]
i have the same issue https://github.com/react-native-community/react-native-elements/issues/39

**Comment by dabit3** [comment]
@crivera @bikashsharmabks just pushed a new version to fix this, thanks for the issue!

**Comment by crivera** [comment]
hi @dabit3 

i have downloaded the latest version and tried to create a FormInput like this:

<FormInput
                  textInputRef='email'
                  autoCorrect={false}
                  keyboardType='default'
                  returnKeyType='next'
                  onChangeText={(val) => {this.setState({'email': val})}}
                  value={this.state.email}
                  placeholder='Email ...'
                  onSubmitEditing={() => {
                     debugger;
                  }}
                />

but when i check the debugger the this.refs object does not have email ref. Any idea why?

**Comment by dabit3** [comment]
Try this:
```
<FormInput
  ref='forminput'
  textInputRef='email'
  ...
/>
```
You should be able to access the refs like: `this.refs.forminput.refs.email` .

**Comment by dabit3** [comment]
@crivera

**Comment by crivera** [comment]
My Hero <3 ! :)

**Comment by dabit3** [comment]
Glad it worked! @crivera

**Comment by MelanieCLopez** [comment]
Thank you ;)
