### ISSUE TITLE
Create React Native Elements Website

### ISSUE THREAD

**Issue by dabit3** [react-native-community/react-native-elements#43]

**Comment by nak1b** [comment]
@dabit3 great components. Not sure if you are looking for any help on the website. Let me know if i can contribute.

**Comment by dabit3** [comment]
@nak1b Hey thanks so much! Yes, I would absolutely love some help with this! I'm thinking of a main page with an overview with some type of side bar to link to each specific component! I'm also open to ideas if you have any examples of sites with good docs you like :) Thanks!

**Comment by nak1b** [comment]
@dabit3 i like [vuejs](https://vuejs.org/api/) api guide.  The sidebar is not very visually appealing but we can work on that. But there docs are easily readable. Also [lodash](https://lodash.com/docs/4.16.1) has great documentation. 

Do you have any other sites in mind?

**Comment by dabit3** [comment]
@nak1b Totally feeling the Vue.js website for sure! What do you think would be the best first steps here? I already have the domain, reactnativeelements.com ..

**Comment by nak1b** [comment]
@dabit3 i guess if you could create repo for the project and base structure we can start working on it from there.

**Comment by dabit3** [comment]
Cool. Just set up a repo for the site at https://github.com/dabit3/react-native-elements-website and will get to working on a base for us to begin adding to! @nak1b Thanks again for helping out with this, hopefully once we get going some others will join as well :)

**Comment by nak1b** [comment]
cool let me know when the base is ready.

**Comment by sahilthakral23** [comment]
@dabit3 I would also like to be a part of this. Let me know if I can contribute.

**Comment by dabit3** [comment]
@nak1b @sahilthakral23 Thanks so much. I'm in the process of building out the basic home page and an example of what I think would look pretty good as a way to represent the api. Once I'm finished with the basic layout I would love some feedback about how to improve the look and design and once we come to an agreement we can go forward with adding the elements to the menu!

**Comment by benjaminb10** [comment]
Any news about the website?

**Comment by bozzmob** [comment]
@dabit3 @Monte9 I can take this up and come up with a website. Let me know.

**Comment by Monte9** [comment]
@bozzmob I haven't been a part of this project but from the discussion above, it looks like Nader was thinking something along the lines of the [vue.js](https://vuejs.org/v2/api/) website. 

If you wanna get started with it, I am sure @nak1b @sahilthakral23 @benjaminb10 would like to pitch in as well.

**Comment by dabit3** [comment]
@bozzmob Yes you're welcome to get something started with something if you have the chance! @Monte9 and myself can answer any questions, and if @nak1b @sahilthakral23 and @benjaminb10 may still be interested then once you have a blueprint / basic prototype up you can probably get some contributions.

**Comment by bozzmob** [comment]
@dabit3 Awesome! I'll come up with a basic blueprint soon 👍 
And, this is one of the best set of RN-elements/UI I have used or found. Well done guys for maintaining it and developing it.

**Comment by dabit3** [comment]
@bozzmob Awesome! Glad you like using it, it's been a pleasure to work on.

**Comment by Monte9** [comment]
@bozzmob any updates?

**Comment by bozzmob** [comment]
@Monte9 I am very sorry for the delay. I was down with health issues. Now back.
You can have a preview of the website here- [https://bozzmob.github.io/react-native-elements](https://bozzmob.github.io/react-native-elements)

I am cleaning up the code/md. Will send a pull request by today EOD.

**Comment by dabit3** [comment]
@bozzmob @Monte9 Looking really nice!

**Comment by bozzmob** [comment]
@dabit3 I am unable to create a pull request. The branch is 'gh-pages' which doesn't exist in the main repo but exists on my fork. Please can you add me as a collaborator to this project, so that I can easily setup the website?

**Comment by Monte9** [comment]
@bozzmob Hope you are feeling better now. The website looks amazing! GJ! 

Is it possible for you to create a simple ToDo List for things that are still needed to be done before it goes live? There are a few folks here that are willing to help out if needed.

**Comment by bozzmob** [comment]
@Monte9 Yes. I'm feeling better now. Thanks.
Happy to know the website looks good.
Yes I'll add a README on how to edit it, run it locally, build it and publish it.
Also will add To Do list.

**Comment by bozzmob** [comment]
@dabit3 It would be easy to test on gh-pages branch for me without affecting the flow of the master. Would like to deploy the site and then make changes as we need. Please can you add me as collaborator?

**Comment by dabit3** [comment]
@bozzmob sure thing, I'll add you right away!

**Comment by bozzmob** [comment]
@dabit3 I have merged the code. Need to add README and enhance few things still. But, you need to enable pages in github repo settings. I don't have access to it, since I'm not a member I guess. Please can you do it? Point the github pages to 'gh-pages' branch.

**Comment by Monte9** [comment]
@bozzmob I believe I has access to the settings. I can take care of this for you today. Will ping you once it's done.

**Comment by bozzmob** [comment]
@Monte9 sure. let me know.

**Comment by Monte9** [comment]
@bozzmob Can you share your email with me so that I can reach out to you? Thanks.

**Comment by bozzmob** [comment]
satvik [dot] jagannath7 [at] gmail.com

**Comment by Monte9** [comment]
In an effort to streamline all RNE issues such that it is easier to get to solutions faster/ submit a new issue we have decided to close any enhancement/roadmap features as "issues". 

Feel free to use this issue to talk about this feature and ping @binoy14 or me (@monte9) if you feel like you can submit a PR for this. Thanks in advance.

Also you can track the status of this feature and all other roadmap features [here](https://github.com/react-native-community/react-native-elements/issues/195#issuecomment-286213704).

**Comment by camillo777** [comment]
Why not use these components on the website? 
It would be just self explaining! And cool! 
So you can start with web compatibility.

**Comment by binoy14** [comment]
@camillo777 It could be nice but would require lot of effort for setting it up. Maybe could be something we can look at in the next version of the site.

**Comment by yeknava** [comment]
i can help with this too, i have some backend knowledge also if needed, ping me for any help.

**Comment by Monte9** [comment]
@yeknava thanks for offering. We are using MKDocs to generate the website using the Readme.md

It's already live. You can check it out here: https://react-native-training.github.io/react-native-elements/

With that being said, I am curious to know what you think about it? If you could refactor it to make it friendlier & easier to read for beginners, how would you do it?

**Comment by yeknava** [comment]
@Monte9 its fine for this version, for UX reasons i think API menu should be open by default and by scrolling i like to see left menu change its active item, also if site uses full of screen in width it will be better in my eyes.
later we can use `react native web` to let user work with components on doc.

**Comment by camillo777** [comment]
Also home page is too long.
Should be split into different pages like it is when clicking on the Api
menu items.
Camillo

Il 03 Apr 2017 9:36 PM, "yeknava" <notifications@github.com> ha scritto:

**Comment by binoy14** [comment]
@camillo777 yes your right, our plan is once release is merge we will change the home page to be more website friendly

**Comment by Monte9** [comment]
@camillo777 @yeknava That's great feedback! Thanks. 

Do you both wanna help us make the website awesome 💯 ?

**Comment by camillo777** [comment]
Yes sure, I would be pleased to help! 
Camillo

**Comment by Monte9** [comment]
Awesome @camillo777. 

I'll put together a list of "good first task" TODO list for the website. Will add it here once I do so.

**Comment by camillo777** [comment]
Hi. I have uploaded a video of mobile rendering on Android it seems there is some layer missing on the menu header; it should not scroll the background :

https://youtu.be/Sbt0JC2GJVo

And I would advice that, on mobile,  tapping out of the menu would automatically close the menu without have to click on the arrow. 
With big screen phone it is annoying to go from right edge to left edge of the phone.

**Comment by binoy14** [comment]
@camillo777 great catch but I think it truly belongs to be reported here https://github.com/squidfunk/mkdocs-material we are using mkdocs material theme. We did not customize it yet

**Comment by yeknava** [comment]
@Monte9 sure

**Comment by camillo777** [comment]
yes, but I do not know what version you are using

2017-04-04 12:20 GMT+02:00 yeknava <notifications@github.com>:

**Comment by binoy14** [comment]
Take a look at v0.11.0 that has all the latest code. Once you clone it locally and install all the requirements.

`pip install mkdocs mkdocs-material pymdown-extensions`

You can run it locally using `mkdocs serve` feel free to make any PRs to v0.11.0 branch

**Comment by Monte9** [comment]
@camillo777 @yeknava This is prob a good place to start:

1. Refactor readme to link directly to the docs and get rid of all the API stuff from the readme. 
2. Updating docs folder with latest readme changes
3. UI polish
4. Other enchantments?

**Comment by camillo777** [comment]
I have got an answer for the mkdocs-material theme:

"As written, sadly the scroll-through is not fixable. However, I provided a fix for the unresponsive overlay which was fixed with #264 and is now in master. Can you test it? I can only test on the Android emulator and it may not be accurate enough."

And There should be a new release fixing some layer stuff:

"Fixed and released in 1.5.4"
