### ISSUE TITLE
Access Denied Error

### ISSUE THREAD

**Issue by javismiles** [react-native-community/react-native-elements#44]
When using I get an access denied error:

Error: java.io.FileNotFoundException: C:\2016\react\react-native-audio\AudioExample\android\app\build\intermediates\assets\debug\fonts\MaterialIcons.ttf (Access is denied)

**Comment by dabit3** [comment]
This definitely look like an error with the installation Material Icons. Have you been able to install the material icons alone to see if you can get them up and running @javismiles  ?

**Comment by dabit3** [comment]
@javismiles check out [this thread](https://github.com/react-native-community/react-native-elements/issues/12)
