### ISSUE TITLE
errors when using size property in icon

### ISSUE THREAD

**Issue by YangLu94** [react-native-community/react-native-elements#49]
when i use the property of size in icon,the react-native will have a mistake.
i have tried two ways to solve this problem,but there still exists.
 1.<Icon
                raised
                name='heartbeat'
                type='octicon'
                color='#f50'
                size={30}
                onPress={() => alert('hello')}
                />
2.
<Icon
                raised
                name='heartbeat'
                type='octicon'
                color='#f50'
                size='30'
                onPress={() => alert('hello')}
                />
Error while updating property 'borderRadius' of a view managed by:RCTView

**Comment by dabit3** [comment]
I'm unable to find the `heartbeat` icon in octicons, but when I use the `heart` with all of the other props the same, it seems to work. Check out the octicon icons [here](https://octicons.github.com/) and let me know if this solves the issue.

**Comment by YangLu94** [comment]
Sorry to make a such stupid mistake,i changed the icon and the problem was solved,  Thx a lot,

**Comment by dabit3** [comment]
@YangLu94 No worries, glad it helped :)
