### ISSUE TITLE
Image Prop on Card Component

### ISSUE THREAD

**Issue by rajinwonderland** [react-native-community/react-native-elements#51]
Hey there,

Having a bit of trouble passing images to the image props on the card component.

Has this been implemented yet or am I passing the image props incorrectly?:

```
  <Card
     image={require('../Images/myImage.png')}
  >
```

Any help on this would be greatly appreciated!

**Comment by dabit3** [comment]
Hey, I just tested this and is seems to be working on my end. Is there any type of error message you're getting? @rajinwonderland

**Comment by rajinwonderland** [comment]
I'm just receiving an unable to resolve error message

**Comment by andrerfneves** [comment]
@rajinwonderland are you on Android or iOS?

**Comment by rajinwonderland** [comment]
ios!

**Comment by patbaker82** [comment]
@rajinwonderland Do images load otherwise outside the component?

**Comment by rajinwonderland** [comment]
Yes, all images load outside of the component. I'm using the components on an ignite react-native stack. I'm not sure if there might be conflicting configurations?

**Comment by Monte9** [comment]
@rajinwonderland are you still running into this issue?
