### ISSUE TITLE
More Elements?

### ISSUE THREAD

**Issue by andrerfneves** [react-native-community/react-native-elements#55]
Hey @dabit3, I was looking through the list of Components that RN Elements has and I was wondering if there were any other ones that you'd think are worth building (or some that might be worth expanding on)? I'm taking a look at RN Swipable ListItem and am planning on doing an implementation for RN Elements, but maybe there are more pressing needs/issues that need to be attended to. Also saw the chat about RN Elements Website on #43, which I'm sure I can help with too.

**Comment by dabit3** [comment]
@andrerfneves definitely appreciate any feedback about what would be a good addition. Feel free to open issues about any components you would like to see  :) comment on the website thread to join us in building it out! I'll be sure to notify you as we get going. The main thing there is for me to upload the initial layout so we have something to go by. I should have something there by next week at the latest!

**Comment by Monte9** [comment]
@andreioprisan there are a few components currently in the pipeline. If you have bandwidth and want to work on any of them, your help would be much appreciated. 
#29 
#15 
#43 
#94
