### ISSUE TITLE
Create Activity Indicator for elements

### ISSUE THREAD

**Issue by Jeanmsilva89** [react-native-community/react-native-elements#56]
I was wondering if other people would be interested in Loading Indicator prop for elements such as a Button and FormInput. I'm thinking of just adding a prop called "loading" and it would wrap the ActivityIndicator in the button container for example. 

Before creating a PR, I wanted to know if there would be interest from the community on such feature.

Thanks.

**Comment by dabit3** [comment]
I think this would be a great addition for sure! @Jeanmsilva89

**Comment by Firaenix** [comment]
I'd love something like this for my project!

**Comment by Jeanmsilva89** [comment]
#62

**Comment by Jeanmsilva89** [comment]
I'd love to add this feature to other components, and I'll have to do it for my own projects so I'll submit another PR soon for that.
@dabit3 Another topic but figured I'd ask you here instead of opening another issue. 
Is there a reason for why you decided to create the SocialIcon component from scratch as opposed to building it on top of your button component? In a lot of ways the social media icons are used as buttons and could share lot of the button features. 
For example. I just created a branch where I replicated the props. "small, disabled, loading" into the socialIcon component. I initially assumed it was built using the button so I thought it would've just worked. 

Btw thanks a lot for this cool project and for you awesome React Native Radio, been really enjoying it big time. Keep up!

**Comment by Monte9** [comment]
@Jeanmsilva89 I really like what you have done with the activity indicators on the button elements. gj!
What other components were you thinking of adding the activity indicator too?

Also I think, as part of your PR you forgot to update the readme with the new button props that you implemented. Feel free to submit a PR for this if you are not busy.

**Comment by dekm** [comment]
Would be cool to have this added to the Searchbar as well.  I was just trying to look into adding a spinner on the right side of the searchbar as I'm calling search as the user types.

Looks like inside the search component there is only the left icon currently added.

**Comment by Jeanmsilva89** [comment]
@Monte9 Sorry I have been too busy in the past few weeks, and missed your comment. I'll send a PR for the README by this weekend. 

@dekm I'm not using the SearchBar currently but yeah I think it's useful for just about every component that has an onPress event so that a loading state can be added.

**Comment by Monte9** [comment]
@Jeanmsilva89 any updates?

**Comment by Monte9** [comment]
@binoy14 since we haven't heard from Jean, maybe this is something we can do ourselves. We can talk about what elements it would make sense to add the activityIndicator to. 

Also, reading his comment above about SocialIcon not built on top of Button makes sense. I wonder why this is case? Could we possibly refactor?

**Comment by binoy14** [comment]
@Monte9 SearchBar has a activity indicator, was recently added. 

I agree with changing socialIcon to Button

**Comment by Monte9** [comment]
Closing this issue as PR (https://github.com/react-native-community/react-native-elements/pull/62) has been merged

The Button -> SocialIcon refactor is unrelated to this issue. @binoy14 I'll follow-up with you on this and put it on our TODO list.

**Comment by jasan-s** [comment]
How can I add a spinner to a button conditionally ?

**Comment by binoy14** [comment]
You can add loading prop. It's not documented currently but should be
