### ISSUE TITLE
Search bar no longer working

### ISSUE THREAD

**Issue by elie222** [react-native-community/react-native-elements#57]
This code:

```
      <SearchBar
        lightTheme
        onChangeText={onChangeSearchText}
        placeholder="Search Players..."
      />
```

Is causing this crash:
<img width="386" alt="screen shot 2016-10-02 at 3 41 11 am" src="https://cloud.githubusercontent.com/assets/3090527/19017812/339234c0-8852-11e6-9dc0-2020d6926171.png">

**Comment by elie222** [comment]
The issue is that SearchBar isn't being exported from this package although I don't know why. The code seems fine

**Comment by michelre** [comment]
I encountered the issue too and resolved it by using another name instead of SearchBar. If I use something like`import { SearchBar as _SearchBar } from 'react-native-elements'`, it's working pretty well!

**Comment by dabit3** [comment]
Just pushed a new release and this is fixed, thanks for the feedback and pointing this out! Best.
