### ISSUE TITLE
ListView Component large dataset with external images bug

### ISSUE THREAD

**Issue by mobinni** [react-native-community/react-native-elements#65]
Hey there,

I noticed while implementing a list view with your library that you statically render the entire list inside of a view, instead of the React Native ListView component?

Is there a reason for this? You could just as easily wrap around the ListView component, which has multiple performance improvements, including initial list size. This would help when loading large lists with external image resources.

If you'd like I'd be more than willing to open a PR.

Mo

**Comment by dabit3** [comment]
Hey @mobinni, check out https://github.com/react-native-community/react-native-elements#using-rn-listview-implemented-with-link-and-avatar, you're welcome to implement with either a map function or a ListView, it's really up to you! Let me know if I may have missed something or misunderstood your question. thanks!
