### ISSUE TITLE
Can I change the search bar icon position?

### ISSUE THREAD

**Issue by wfsovereign** [react-native-community/react-native-elements#69]
I have a requirement, I want to change the search bar icon position, because the icon is absolute and no via to change it. 

The existing includes:
* containerStyle
* inputStyle
* icon
* noIcon
* lightTheme
* round
* containerRef
* textInput

**Comment by wfsovereign** [comment]
I find a method by code source, by icon.style can change the icon

**Comment by abury** [comment]
For anyone else that might come along looking for this, the search bar icon prop takes an object that accepts a `styles key, so you can do something like so:

````
const styles = {
    searchBarContainer: {...},
    iconStyle: {
        left: 10
    }
}
<SearchBar
    containerStyle={styles.searchBarContainer}
    icon={{ type: 'material', color: '#86939e', name: 'search', style: styles.iconStyle }} />
```
