### ISSUE TITLE
Tab 'selected=true' causes React.Children.only error

### ISSUE THREAD

**Issue by danikenan** [react-native-community/react-native-elements#71]
The simplest scenario for tabs:

``` js
const TabPanel = () => (
  <Tabs>
    <Tab title="a" selected={true}/>
    <Tab title="b"/>
  </Tabs>
);
```

Causes an error

> “React.Children.only expected to receive a single React element child”

If one **removes** the `selected={true}` or **changes** to `selected={false}` it works.

**Comment by dabit3** [comment]
Any way you can show more code, I'm unable to duplicate this. thanks.

**Comment by jacobcyl** [comment]
I get the same Error if I add attribute "selected". But when I remove selected tag , It work or if I set selected={false} It work again.

**Comment by Monte9** [comment]
@jacobcyl Unable to reproduce this. Can you show me the code that is causing this error?

**Comment by jacobcyl** [comment]
I found the answer! because the <Tab> tag must contain a child element. We should do it like this:
```php
<Tabs>
  <Tab>
    <SomeOtherComponent />
 </Tab>
</Tabs>
```
