### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by xcarpentier** [react-native-community/react-native-elements#80]
Is it possible to change global style : Colors, border, shadow, ... in configuration/initialisation phase ?

**Comment by patbaker82** [comment]
@xcarpentier From what I can see the components to do follow a theming implementation.  I had the same question and poked around the code.  It looks like the colors have named exports and are directly imported to each component.

**Comment by dabit3** [comment]
Don't think this is possible right now, feel free to submit a pr if you think you have an idea how to implement, but for now I'm going to close this.
