### ISSUE TITLE
Update react-native-vector-icons peer dependency to ~3.0.0

### ISSUE THREAD

**Issue by brentvatne** [react-native-community/react-native-elements#82]
As title says!

**Comment by r3verser** [comment]
Got error while installing:

> +-- react-native-elements@0.6.3
| `-- react-native-tab-navigator@0.3.3
|   `-- immutable@3.8.1
`-- UNMET PEER DEPENDENCY react-native-vector-icons@3.0.0
npm WARN react-native-elements@0.6.3 requires a peer of react-native-vector-icons@^2.1.0 but none was installed.

**Comment by GtAntoine** [comment]
Same problem as r3verser. I have this error on windows when I try to work with https://github.com/react-native-community/react-native-elements. Also when I simply try to use vector icon on another project.

**Comment by RailtonMatthew** [comment]
I get the same error also.  Worked fine on another project I created a few weeks ago.

+-- react-native-elements@0.6.3
`-- UNMET PEER DEPENDENCY react-native-vector-icons@3.0.0

npm WARN react-native-elements@0.6.3 requires a peer of react-native-vector-icons@^2.1.0 but none was installed.

**Comment by 1169458576** [comment]
me too

**Comment by ataomega** [comment]
any solutions?

**Comment by dabit3** [comment]
@ataomega @1169458576 @RailtonMatthew @GtAntoine @r3verser @brentvatne Just updated this, let me know if you have any issues. Sorry for the delay!

**Comment by datnguyen0606** [comment]
Hi, I get the same issue on Mac, is it resolved yet?

**Comment by abrarsheikh** [comment]
@datnguyen0606 please follow the installation instruction on https://github.com/react-native-community/react-native-elements.

i ran into the similar problem when i tried to install directly using `npm isntall`

**Comment by 839588378** [comment]
could you tell me how to do ?please!@dabit3

**Comment by henrydeclety** [comment]
still getting this issue on mac

**Comment by binoy14** [comment]
@839588378 and @henrydeclety what issue are you having?

**Comment by LAITONEN** [comment]
@binoy14  I am getting this warning in Expo:
Warning: 'react-native-vector-icons' peer depencency missing. Run `npm ls` in /Users/JohnSmith/workspace/MyApps/cat_pic-scroller to see full warning.

If there is an issue running your project, please run `npm install` in /Users/JohnSmith/workspace/MyApps/cat_pic_scroller and restart.
