### ISSUE TITLE
textInputRef doesn't work

### ISSUE THREAD

**Issue by joevo2** [react-native-community/react-native-elements#84]
I couldn't do next keyboard input, the ref doesn't seems to be working

**Comment by joevo2** [comment]
`<View style={{ flex: 1, height: 100, }}>
					<TextInput
						ref='1'
						style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
						placeholder='Normal'
						returnKeyType='next'
						blurOnSubmit={false}
						onSubmitEditing={()=>{this._focusNextField('2')}}
						/>
					<TextInput
						ref='2'
						style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
						keyboardType='email-address'
						placeholder='Email Address'
						returnKeyType='next'
						blurOnSubmit={false}
						onSubmitEditing={()=>{this._focusNextField('3')}}
						/>
				</View>
          <FormLabel>{language.name}</FormLabel>
          <FormInput
						textInputRef={'3'}
						inputStyle={styles.formInput}
            onChangeText={(text) => this.setState({name: text})}
						autoCapitalize={'words'}
						returnKeyType={"next"}
						placeholder={'Please enter your name'}
						blurOnSubmit={false}
						onSubmitEditing={()=>{this._focusNextField('4')}}
          />`

**Comment by joevo2** [comment]
```
<View style={{ flex: 1, height: 100, }}>
					<TextInput
						ref='1'
						style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
						placeholder='Normal'
						returnKeyType='next'
						blurOnSubmit={false}
						onSubmitEditing={()=>{this._focusNextField('2')}}
						/>
					<TextInput
						ref='2'
						style={{ height: 40, borderColor: 'gray', borderWidth: 1 }}
						keyboardType='email-address'
						placeholder='Email Address'
						returnKeyType='next'
						blurOnSubmit={false}
						onSubmitEditing={()=>{this._focusNextField('3')}}
						/>
				</View>
          <FormLabel>{language.name}</FormLabel>
          <FormInput
						textInputRef={'3'}
						inputStyle={styles.formInput}
            onChangeText={(text) => this.setState({name: text})}
						autoCapitalize={'words'}
						returnKeyType={"next"}
						placeholder={'Please enter your name'}
						blurOnSubmit={false}
						onSubmitEditing={()=>{this._focusNextField('4')}}
          />
```

**Comment by dabit3** [comment]
Try something like this:

```
<FormInput
  ref='forminput'
  textInputRef='email'
  ...
/>
```

I know the docs are not 100% clear on this, let me know if this helps, and I'll attempt to clarify this in the docs as well.

**Comment by housseindjirdeh** [comment]
In case anyone experiences the same issue, I was having the same problem with `searchBar`. @dabit3's solution solved the problem :)

**Comment by xiaogaozi** [comment]
Maybe we should document this in Searchbar too?

**Comment by Monte9** [comment]
@xiaogaozi sure thing. Feel free to submit a PR if you can. ⚡️
