### ISSUE TITLE
Update logo?

### ISSUE THREAD

**Issue by swaffoja** [react-native-community/react-native-elements#85]
There is a line that runs through your logo that seems odd. I attached a few alternatives in case you want a more natural gradient with your colors.

<img width="200" alt="current" src="https://cloud.githubusercontent.com/assets/887384/20187771/3e626cb4-a73b-11e6-96e9-451571368b85.png">

![react-gradient-v1](https://cloud.githubusercontent.com/assets/887384/20187568/6691d6ee-a73a-11e6-878a-6a47e8c83c6e.png)
![react-gradient-v2](https://cloud.githubusercontent.com/assets/887384/20187976/2f35724e-a73c-11e6-9423-cc4fc76bc029.png)

**Comment by dabit3** [comment]
@swaffoja This logo looks amazing!!! Thanks so much, I'm going to update everything with this if it's ok with you.

**Comment by swaffoja** [comment]
@dabit3 Sure, have at it.

**Comment by dabit3** [comment]
Thanks!
