### ISSUE TITLE
Requiring unknown module react-native-elements

### ISSUE THREAD

**Issue by tsvetann** [react-native-community/React-Native-Elements#9]
After installing the module I get an error:

> Requiring unknown module react-native-elements

The module is there but I cannot see the entry script.

**Comment by dabit3** [comment]
What version of React Native are you using? Also, I'm sure you've already tried restarting your packager?

**Comment by tsvetann** [comment]
Yep restarting the packager solved it. Should've thought about it myself. Thx @dabit3

**Comment by dabit3** [comment]
Awesome!
