### ISSUE TITLE
hitSlop button is missing

### ISSUE THREAD

**Issue by note89** [react-native-community/react-native-elements#92]
https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#props
hitSlop is missing from `button`
https://github.com/react-native-community/react-native-elements/blob/master/src/buttons/Button.js#L31

**Comment by Monte9** [comment]
Thanks for adding this in @note89! (https://github.com/react-native-community/react-native-elements/commit/01fcbb91ddd607eb9d81b60c93ff474a9546b834)
 Closing this issue now.
