### ISSUE TITLE
Margin top on list element

### ISSUE THREAD

**Issue by Andersos** [react-native-community/react-native-elements#95]
`Default: none` for the [List Props](https://github.com/react-native-community/react-native-elements#list-props) seems to be incorrect. Looks like there is some default marginTop of [20](https://github.com/react-native-community/react-native-elements/blob/master/src/list/List.js#L16). Is this something that should be listed?

**Comment by dabit3** [comment]
Thanks @Andersos !

**Comment by Andersos** [comment]
Next time I will send a pull request. Was unsure if it was on purpose or not.

**Comment by dabit3** [comment]
Cool, no problem 💯

**Comment by RWOverdijk** [comment]
I can't seem to find how to get rid of the margin

**Comment by binoy14** [comment]
@RWOverdijk did you try using containerStyle ? take a look at the props https://react-native-training.github.io/react-native-elements/API/lists/#list-props

**Comment by RWOverdijk** [comment]
@binoy14 Yeah I'm an idiot. Sorry
