### ISSUE TITLE
Height for ImageStyle in Card not work

### ISSUE THREAD

**Issue by qiluo** [react-native-community/react-native-elements#96]
Hi, I've create below stub
```
<Card title='Toothbrush'
        image={require('./images/toothbrush.png')}
        imageStyle={{height:100, width:320}}>
....
</Card>
```

The width worked well, but didn't height, what's wrong with me? thanks

**Comment by binoy14** [comment]
Works for me, I am using it inside scrollview. Not sure if that has to do anything with that.

**Comment by dabit3** [comment]
@qiluo , I'm unable to reproduce. Can you specify what version or RN you are using and what platform this is on (iOS or Android)? thanks!

**Comment by Monte9** [comment]
@qiluo any updates on this? If not, then I'll close this issue as it's not reproducible.

**Comment by AbdulRahman-Proxcurity** [comment]
How to position image tag inside card tag center
