### ISSUE TITLE
A segment is necessary

### ISSUE THREAD

**Issue by zhangruinian** [react-native-community/react-native-elements#97]
maybe it is simple to use icon button to do segment?

**Comment by Monte9** [comment]
@zhangruinian When you say `segment`.. are you thinking about something like `UISegmentedControl` on iOS?

**Comment by Monte9** [comment]
@zhangruinian any updates on this?

**Comment by Monte9** [comment]
For now consider using https://github.com/lelandrichardson/react-native-segmented-view

We might add this to RNE in the future.
